---
identifier: "CVE-2019-10223"
package_slug: "go/github.com/kubernetes/kube-state-metrics"
title: "Information Exposure"
description: "A security issue was discovered in the kube-state-metrics versions.
  By default, the kube-state-metrics metrics only expose metadata about Secrets. However,
  a combination of the default `kubectl` behavior and this new feature can cause the
  entire secret content to end up in metric labels thus inadvertently exposing the
  secret content in metrics."
date: "2019-11-29"
pubdate: "2019-11-05"
affected_range: ">=v1.7.0 <=v1.7.1"
fixed_versions:
- "v1.7.2"
affected_versions: "All versions starting from 1.7.0 up to 1.7.1"
_git_import_path: "go/github.com/kubernetes/kube-state-metrics"
not_impacted: "All versions before 1.7.0, all versions after 1.7.1"
solution: "Upgrade to version 1.7.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-10223"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10223"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
uuid: "23dc9fbd-85ce-4a19-94ea-a1be0c2365ae"
versions:
- number: "v1.7.0"
  commit:
    tags:
    - "v1.7.0"
    sha: "29d53cece3243ed6df721ec185a17f29a8ea8412"
    timestamp: "20190718050012"
- number: "v1.7.1"
  commit:
    tags:
    - "v1.7.1"
    sha: "0656e3ee5641f2cf5a9b7ccd33603790759f2abb"
    timestamp: "20190720013855"
- number: "v1.7.2"
  commit:
    tags:
    - "v1.7.2"
    sha: "8657a933105965e0c31894f63a8b38bff4f4b190"
    timestamp: "20190805171549"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2019-10223"
