---
identifier: "CVE-2018-1000149"
package_slug: "maven/org.jenkins-ci.plugins/ansible"
title: "Improper Certificate Validation"
description: "A man in the middle vulnerability exists in the Jenkins Ansible Plugin
  that disables host key verification by default."
date: "2018-05-15"
pubdate: "2018-04-05"
affected_range: "(,0.8]"
fixed_versions:
- "1.0"
affected_versions: "All versions up to 0.8"
not_impacted: "All versions after 0.8"
solution: "Upgrade to version 1.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1000149"
- "https://jenkins.io/security/advisory/2018-03-26/#SECURITY-630"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L"
uuid: "6b2998c0-14ff-4ae2-a1d0-ad6afe3fb8fa"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2018-1000149"
