---
identifier: "CVE-2020-8558"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Improper Authentication"
description: "The Kubelet and kube-proxy components were found to contain a security
  issue which allows adjacent hosts to reach TCP and UDP services bound to running
  on the node or in the node's network namespace. Such a service is generally thought
  to be reachable only by other processes on the same host, but due to this defeect,
  could be reachable by other hosts on the same LAN as the node, or by containers
  running on the same node as the service."
date: "2020-08-21"
pubdate: "2020-07-27"
affected_range: ">=1.1.0 <=1.16.10||>=1.17.0 <=1.17.6||>=1.18.0 <=1.18.3"
fixed_versions:
- "1.16.11"
- "1.17.7"
- "1.18.4"
affected_versions: "All versions starting from 1.1.0 up to 1.16.10, all versions starting
  from 1.17.0 up to 1.17.6, all versions starting from 1.18.0 up to 1.18.3"
not_impacted: "All versions starting from 1.16.11 before 1.17.6, all versions starting
  from 1.17.7 before 1.18.3, all versions starting from 1.18.4"
solution: "Upgrade to version 1.16.11, 1.17.7, 1.18.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8558"
cvss_v2: "AV:A/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "29831df3-8f66-4a00-84f2-eef73ba403e1"
cwe_ids:
- "CWE-1035"
- "CWE-287"
- "CWE-937"
identifiers:
- "CVE-2020-8558"
