---
identifier: "CVE-2020-8551"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Allocation of Resources Without Limits or Throttling"
description: "The Kubelet component has been found to be vulnerable to a denial of
  service attack via the kubelet API, including the unauthenticated HTTP read-only
  API typically served on port, and the authenticated HTTPS API typically served on
  port "
date: "2020-07-24"
pubdate: "2020-03-27"
affected_range: ">=1.15.0 <=1.15.9||>=1.16.0 <=1.16.6||>=1.17.0 <=1.17.2"
fixed_versions: []
affected_versions: "All versions starting from 1.15.0 up to 1.15.9, all versions starting
  from 1.16.0 up to 1.16.6, all versions starting from 1.17.0 up to 1.17.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8551"
cvss_v2: "AV:A/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "1af54d65-751b-4e31-9eed-4907810dc34f"
cwe_ids:
- "CWE-1035"
- "CWE-770"
- "CWE-937"
identifiers:
- "CVE-2020-8551"
