---
identifier: "CVE-2021-25735"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Incorrect Authorization"
description: "A security issue was discovered in kube-apiserver that could allow node
  updates to bypass a Validating Admission Webhook.Validating Admission Webhook does
  not observe some previous fields."
date: "2021-09-13"
pubdate: "2021-09-06"
affected_range: "<1.18.18||>=1.19.0 <1.19.10||>=1.20.0 <1.20.6"
fixed_versions:
- "1.18.18"
- "1.19.10"
- "1.20.6"
affected_versions: "All versions before 1.18.18, all versions starting from 1.19.0
  before 1.19.10, all versions starting from 1.20.0 before 1.20.6"
not_impacted: "All versions starting from 1.18.18 before 1.19.0, all versions starting
  from 1.19.10 before 1.20.0, all versions starting from 1.20.6"
solution: "Upgrade to version 1.18.18, 1.19.10 or 1.20.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25735"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:H"
uuid: "da9e153f-2eca-4475-9f40-d7a675e3fa1e"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2021-25735"
