---
identifier: "CVE-2020-8564"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Inclusion of Sensitive Information in Log Files"
description: "In Kubernetes clusters using a logging level of at least 4, processing
  a malformed docker config file will result in the contents of the docker config
  file being leaked, which can include pull secrets or other registry credentials."
date: "2021-03-29"
pubdate: "2020-12-07"
affected_range: ">=1.17.0 <1.17.13||>=1.18.0 <1.18.10||>=1.19.0 <1.19.3"
fixed_versions:
- "1.17.13"
- "1.18.10"
- "1.19.3"
affected_versions: "All versions starting from 1.17.0 before 1.17.13, all versions
  starting from 1.18.0 before 1.18.10, all versions starting from 1.19.0 before 1.19.3"
not_impacted: "All versions starting from 1.17.13 before 1.18.0, all versions starting
  from 1.18.10 before 1.19.0, all versions starting from 1.19.3"
solution: "Upgrade to version 1.17.13, 1.18.10, 1.19.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8564"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "a3654dad-0a43-48b8-815d-5ec58c39baf1"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2020-8564"
