---
identifier: "CVE-2020-8552"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Allocation of Resources Without Limits or Throttling"
description: "The Kubernetes API server component has been found to be vulnerable
  to a denial of service attack via successful API requests."
date: "2020-07-24"
pubdate: "2020-03-27"
affected_range: "<=1.15.9||>=1.16.0 <=1.16.6||>=1.17.0 <=1.17.2"
fixed_versions: []
affected_versions: "All versions up to 1.15.9, all versions starting from 1.16.0 up
  to 1.16.6, all versions starting from 1.17.0 up to 1.17.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8552"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
uuid: "94726479-fd8c-4ee3-8d2b-f9c888e70033"
cwe_ids:
- "CWE-1035"
- "CWE-770"
- "CWE-937"
identifiers:
- "CVE-2020-8552"
