---
identifier: "CVE-2020-8563"
package_slug: "go/k8s.io/kubernetes/pkg/apis/apps/validation"
title: "Inclusion of Sensitive Information in Log Files"
description: "In Kubernetes clusters using VSphere as a cloud provider, with a logging
  level set to 4 or above, VSphere cloud credentials will be leaked in the cloud controller
  manager's log."
date: "2021-03-29"
pubdate: "2020-12-07"
affected_range: "<1.19.3"
fixed_versions:
- "1.19.3"
affected_versions: "All versions before 1.19.3"
not_impacted: "All versions starting from 1.19.3"
solution: "Upgrade to version 1.19.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8563"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "baf85d13-20e0-4673-a28b-2a212b7a1fb2"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2020-8563"
