---
identifier: "CVE-2020-4053"
identifiers:
- "GHSA-qq3j-xp49-j73f"
- "CVE-2020-4053"
package_slug: "go/helm.sh/helm/v3"
title: "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
description: "In Helm greater than or equal to 3.0.0 and less than 3.2.4, a path traversal
  attack is possible when installing Helm plugins from a tar archive over HTTP. It
  is possible for a malicious plugin author to inject a relative path into a plugin
  archive, and copy a file outside of the intended directory. This has been fixed
  in 3.2.4."
date: "2023-10-02"
pubdate: "2021-06-23"
affected_range: ">=v3.0.0 <v3.2.4"
fixed_versions:
- "v3.2.4"
affected_versions: "All versions starting from 3.0.0 before 3.2.4"
not_impacted: "All versions before 3.0.0, all versions starting from 3.2.4"
solution: "Upgrade to version 3.2.4 or above."
urls:
- "https://github.com/helm/helm/security/advisories/GHSA-qq3j-xp49-j73f"
- "https://nvd.nist.gov/vuln/detail/CVE-2020-4053"
- "https://github.com/helm/helm/pull/8317"
- "https://github.com/helm/helm/commit/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688"
- "https://github.com/helm/helm/commit/b6bbe4f08bbb98eadd6c9cd726b08a5c639908b3"
- "https://github.com/helm/helm/releases/tag/v3.2.4"
- "https://github.com/advisories/GHSA-qq3j-xp49-j73f"
cvss_v2: "AV:N/AC:M/Au:S/C:C/I:C/A:C"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:H/I:H/A:H"
uuid: "ab9e1fa2-4e77-4cb1-bf18-0eb3ccc6e650"
cwe_ids:
- "CWE-1035"
- "CWE-22"
- "CWE-78"
- "CWE-937"
versions: []
