---
identifier: "CVE-2025-0495"
identifiers:
- "CVE-2025-0495"
- "GHSA-m4gq-fm9h-8q75"
package_slug: "go/github.com/docker/buildx"
title: "buildx allows a possible credential leakage to telemetry endpoint"
description: "Some cache backends allow configuring their credentials by setting secrets
  directly as attribute values in `cache-to/cache-from` configuration. If this was
  done by the user, these secure values could be captured together with OpenTelemetry
  trace as part of the arguments and flags for the traced CLI command. Passing tokens
  to Github cache backend via environment variables or using registry authentication
  is not affected.\n\nIf you passed a token value like this and use a custom OpenTelemetry
  collector for computing traces you should make sure that your traces are kept secure.
  OpenTelemetry traces are also saved in BuildKit daemon's history records."
date: "2025-10-31"
pubdate: "2025-03-17"
affected_range: "<0.21.3"
fixed_versions:
- "0.21.3"
affected_versions: "All versions before 0.21.3"
not_impacted: "All versions starting from 0.21.3"
solution: "Upgrade to version 0.21.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-0495"
- "https://github.com/advisories/GHSA-m4gq-fm9h-8q75"
- "https://github.com/docker/buildx/security/advisories/GHSA-m4gq-fm9h-8q75"
- "https://github.com/docker/buildx/commit/18ccba072076ddbfb0aeedd6746d7719b0729b58"
- "https://github.com/docker/buildx"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:C/C:H/I:N/A:N"
cvss_v4: "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:P/VC:L/VI:N/VA:N/SC:H/SI:N/SA:N"
uuid: "450b97a1-cbb3-4c32-848d-ac93c64adb25"
cwe_ids:
- "CWE-532"
- "CWE-937"
- "CWE-1035"
