---
identifier: "CVE-2015-6240"
package_slug: "pypi/ansible"
title: "Possible escape from confined environment"
description: "Improprer symlink handling in zone, jail, and chroot connection plugins
  could lead to escape from confined environment. File copying is not performed by
  code that is operating within the restricted environment (chroot, jail, or zone)."
date: "2019-09-16"
pubdate: "2017-06-07"
affected_range: "<1.9.2"
fixed_versions:
- "1.9.2"
affected_versions: "All versions before 1.9.2"
not_impacted: "All versions starting from 1.9.2"
solution: "Upgrade to version 1.9.2 or above."
urls:
- "http://www.ansible.com/security"
- "https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#192-dancing-in-the-street---jun-26-2015"
- "https://github.com/ansible/ansible/commit/952166f48eb0f5797b75b160fd156bbe1e8fc647"
- "https://github.com/ansible/ansible/commit/ca2f2c4ebd7b5e097eab0a710f79c1f63badf95b"
cvss_v2: "AV:L/AC:L/Au:N/C:C/I:C/A:C"
cvss_v3: "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "5e23936b-a2a3-4a01-917e-c8bc29f60d5e"
cwe_ids:
- "CWE-1035"
- "CWE-59"
- "CWE-937"
identifiers:
- "CVE-2015-6240"
