---
identifier: "CVE-2019-14858"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "A vulnerability was found in Ansible. When a module has an `argument_spec`
  with sub parameters marked as no_log, passing an invalid parameter name to the module
  will cause the task to fail before the no_log options in the sub parameters are
  processed. As a result, data in the sub parameter fields will not be masked and
  will be displayed if Ansible is run with increased verbosity and present in the
  module invocation arguments for the task."
date: "2019-10-24"
pubdate: "2019-10-14"
affected_range: ">=2.0,<=2.8.0"
fixed_versions:
- "2.8.1"
affected_versions: "All versions starting from 2.0 up to 2.8.0"
not_impacted: "All versions before 2.0, all versions after 2.8.0"
solution: "Upgrade to version 2.8.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-14858"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14858"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
uuid: "817e7cc9-e448-420a-9361-79bbdbcc1e37"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2019-14858"
