---
identifier: "CVE-2021-20191"
identifiers:
- "CVE-2021-20191"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "A flaw was found in ansible. Credentials, such as secrets, are being
  disclosed in console log by default and not protected by no_log feature when using
  those modules. An attacker can take advantage of this information to steal those
  credentials. The highest threat from this vulnerability is to data confidentiality.
  Versions before ansible are affected."
date: "2023-12-28"
pubdate: "2021-05-26"
affected_range: "<2.8.19||>=2.9.0,<2.9.18||>=2.10.0,<2.10.7"
fixed_versions:
- "2.8.19"
- "2.9.18"
- "2.10.7"
affected_versions: "All versions before 2.8.19, all versions starting from 2.9.0 before
  2.9.18, all versions starting from 2.10.0 before 2.10.7"
not_impacted: "All versions starting from 2.8.19 before 2.9.0, all versions starting
  from 2.9.18 before 2.10.0, all versions starting from 2.10.7"
solution: "Upgrade to versions 2.8.19, 2.9.18, 2.10.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-20191"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1916813"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "3bf2e546-4919-4918-80d2-3cb6ef4b7107"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
