---
identifier: "CVE-2020-14332"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "A flaw was found in the Ansible Engine when using `module_args`. Tasks
  executed with check mode (`--check-mode`) do not properly neutralize sensitive data
  exposed in the event data. This flaw allows unauthorized users to read this data.
  The highest threat from this vulnerability is to confidentiality."
date: "2021-08-07"
pubdate: "2020-09-11"
affected_range: ">=2.8.0,<2.8.14||>=2.9.0,<2.9.12"
fixed_versions:
- "2.8.14"
- "2.9.12"
affected_versions: "All versions starting from 2.8.0 before 2.8.14, all versions starting
  from 2.9.0 before 2.9.12"
not_impacted: "All versions before 2.8.0, all versions starting from 2.8.14 before
  2.9.0, all versions starting from 2.9.12"
solution: "Upgrade to versions 2.8.14, 2.9.12 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-14332"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "0ae4bcec-2472-4f80-b886-405bb5bf6137"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2020-14332"
