---
identifier: "CVE-2019-14846"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "Ansible is logging at the DEBUG level which lead to a disclosure of
  credentials if a plugin used a library that logged credentials at the DEBUG level.
  This flaw does not affect Ansible modules, as those are executed in a separate process."
date: "2019-10-21"
pubdate: "2019-10-08"
affected_range: ">=2.0,<=2.8.5"
fixed_versions:
- "2.8.6"
affected_versions: "All versions starting from 2.0 up to 2.8.5"
not_impacted: "All versions before 2.0, all versions after 2.8.5"
solution: "Upgrade to version 2.8.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-14846"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14846"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
uuid: "c7f976a2-abe8-4cda-bbbc-bd869a6cda15"
cwe_ids:
- "CWE-1035"
- "CWE-117"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2019-14846"
