---
identifier: "CVE-2019-10156"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "A flaw was discovered in the way Ansible templating was implemented
  causing the possibility of information disclosure through unexpected variable substitution.
  By taking advantage of unintended variable substitution the content of any variable
  may be disclosed."
date: "2019-09-16"
pubdate: "2019-07-30"
affected_range: "<2.6.18||>=2.7.0,<2.7.12||>=2.8.0,<2.8.2"
fixed_versions:
- "2.6.18"
- "2.7.12"
- "2.8.2"
affected_versions: "All versions before 2.6.18, all versions starting from 2.7.0 before
  2.7.12, all versions starting from 2.8.0 before 2.8.2"
not_impacted: "All versions starting from 2.6.18 before 2.7.0, all versions starting
  from 2.7.12 before 2.8.0, all versions starting from 2.8.2"
solution: "Upgrade to versions 2.6.18, 2.7.12, 2.8.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-10156"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10156"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:P/A:N"
uuid: "dfdabc53-3e3c-49d5-a121-a1027ea54290"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2019-10156"
