---
identifier: "CVE-2019-14856"
package_slug: "pypi/ansible"
title: "Improper Input Validation"
description: "ansible contains a critical vulnerability."
date: "2019-12-11"
pubdate: "2019-11-26"
affected_range: ">=2.6.0,<2.6.20||>=2.7.0,<2.7.14||>=2.8.0,<2.8.6"
fixed_versions:
- "2.6.20"
- "2.7.14"
- "2.8.6"
affected_versions: "All versions starting from 2.6.0 before 2.6.20, all versions starting
  from 2.7.0 before 2.7.14, all versions starting from 2.8.0 before 2.8.6"
not_impacted: "All versions before 2.6.0, all versions starting from 2.6.20 before
  2.7.0, all versions starting from 2.7.14 before 2.8.0, all versions starting from
  2.8.6"
solution: "Upgrade to versions 2.6.20, 2.7.14, 2.8.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-14856"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "12ae57b1-81dc-4752-8c3b-b4aa8d516eeb"
cwe_ids:
- "CWE-1035"
- "CWE-287"
- "CWE-937"
identifiers:
- "CVE-2019-14856"
