---
identifier: "CVE-2020-1736"
package_slug: "pypi/ansible"
title: "Incorrect Permission Assignment for Critical Resource"
description: "A flaw was found in Ansible Engine when a file is moved using `atomic_move`
  primitive as the file mode cannot be specified. This sets the destination files
  world-readable if the destination file does not exist and if the file exists, the
  file could be changed to have less restrictive permissions before the move. This
  could lead to the disclosure of sensitive data."
date: "2021-08-04"
pubdate: "2020-03-16"
affected_range: "<=2.7.16||>=2.8.0,<=2.8.8||>=2.9.0,<=2.9.5"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions up to 2.7.16, all versions starting from 2.8.0 up
  to 2.8.8, all versions starting from 2.9.0 up to 2.9.5"
not_impacted: "All versions after 2.7.16 before 2.8.0, all versions after 2.8.8 before
  2.9.0, all versions after 2.9.5"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1736"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1736"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
uuid: "bbe74831-3b7f-469f-8ebe-28fc2c975bf4"
cwe_ids:
- "CWE-1035"
- "CWE-732"
- "CWE-937"
identifiers:
- "CVE-2020-1736"
