---
identifier: "CVE-2019-10206"
package_slug: "pypi/ansible"
title: "Improper Input Validation"
description: "ansible-playbook -k and ansible cli tools prompt passwords by expanding
  them from templates as they could contain special characters. Passwords should be
  wrapped to prevent templates trigger and exposing them."
date: "2019-12-09"
pubdate: "2019-11-22"
affected_range: ">=2.6.0,<2.6.19||>=2.7.0,<2.7.13||>=2.8.0,<2.8.4"
fixed_versions:
- "2.6.19"
- "2.7.13"
- "2.8.4"
affected_versions: "All versions starting from 2.6.0 before 2.6.19, all versions starting
  from 2.7.0 before 2.7.13, all versions starting from 2.8.0 before 2.8.4"
not_impacted: "All versions before 2.6.0, all versions starting from 2.6.19 before
  2.7.0, all versions starting from 2.7.13 before 2.8.0, all versions starting from
  2.8.4"
solution: "Upgrade to versions 2.6.19, 2.7.13, 2.8.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-10206"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10206"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "3112eab2-64c1-481a-a80b-501466293b09"
cwe_ids:
- "CWE-1035"
- "CWE-20"
- "CWE-937"
identifiers:
- "CVE-2019-10206"
