---
identifier: "CVE-2018-16859"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "Execution of Ansible playbooks on Windows platforms with PowerShell
  ScriptBlock logging and Module logging enabled can allow for 'become' passwords
  to appear in EventLogs in plaintext. A local user with administrator privileges
  on the machine can view these logs and discover the plaintext password."
date: "2019-04-03"
pubdate: "2018-11-29"
affected_range: "<2.5.12 || >=2.6.0.dev0, <2.6.9 || >=2.7.0.dev0, <2.7.3"
fixed_versions:
- "2.5.12"
- "2.6.9"
- "2.7.3"
affected_versions: "All versions before 2.5.12, all versions starting from 2.6.0.dev0
  before 2.6.9, all versions starting from 2.7.0.dev0 before 2.7.3"
solution: "Upgrade to fixed version."
urls:
- "http://www.securityfocus.com/bid/106004"
- "https://access.redhat.com/errata/RHSA-2018:3770"
- "https://access.redhat.com/errata/RHSA-2018:3771"
- "https://access.redhat.com/errata/RHSA-2018:3772"
- "https://access.redhat.com/errata/RHSA-2018:3773"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16859"
- "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16859"
- "https://cwe.mitre.org/data/definitions/200.html"
- "https://github.com/ansible/ansible/commit/8c1f701e6e9df29fe991f98265e2dd76acca4b8c"
- "https://github.com/ansible/ansible/pull/49142"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
uuid: "72b8e9f7-7b4b-4065-ad48-019de54978b5"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2018-16859"
