---
identifier: "CVE-2020-1734"
package_slug: "pypi/ansible"
title: "OS Command Injection"
description: "A flaw was found in the pipe lookup plugin of ansible. Arbitrary commands
  can be run, when the pipe lookup plugin uses `subprocess.Popen()` with `shell=True`,
  by overwriting ansible facts and the variable is not escaped by quote plugin. An
  attacker could take advantage and run arbitrary commands by overwriting the ansible
  facts."
date: "2020-05-29"
pubdate: "2020-03-03"
affected_range: "<=2.7.16||==2.8.8||==2.9.5"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions up to 2.7.16, version 2.8.8, version 2.9.5"
not_impacted: "All versions after 2.7.16 before 2.8.8, all versions after 2.8.8 before
  2.9.5, all versions after 2.9.5"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1734"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1734"
cvss_v2: "AV:L/AC:H/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:C/C:H/I:H/A:L"
uuid: "a1c582f0-6d98-4b2d-bc51-a3ecc81afe51"
cwe_ids:
- "CWE-1035"
- "CWE-78"
- "CWE-937"
identifiers:
- "CVE-2020-1734"
