---
identifier: "CVE-2020-1737"
package_slug: "pypi/ansible"
title: "Path Traversal"
description: "A flaw was found in Ansible when using the `Extract-Zip` function from
  the `win_unzip` module as the extracted file(s) are not checked if they belong to
  the destination folder. An attacker could take advantage of this flaw by crafting
  an archive anywhere in the file system, using a path traversal."
date: "2020-06-13"
pubdate: "2020-03-09"
affected_range: "<2.7.17||>=2.8.0,<2.8.9||>=2.9.0,<2.9.6"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions before 2.7.17, all versions starting from 2.8.0 before
  2.8.9, all versions starting from 2.9.0 before 2.9.6"
not_impacted: "All versions starting from 2.7.17 before 2.8.0, all versions starting
  from 2.8.9 before 2.9.0, all versions starting from 2.9.6"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1737"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1737"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "3fe9aeca-9af6-4821-89e9-ae2efc5733e1"
cwe_ids:
- "CWE-1035"
- "CWE-22"
- "CWE-937"
identifiers:
- "CVE-2020-1737"
