---
identifier: "CVE-2017-7466"
package_slug: "pypi/ansible"
title: "Improper Input Validation"
description: "Ansible has an input validation vulnerability in the handling of data
  sent from client systems. An attacker with control over a client system being managed
  by Ansible, and the ability to send facts back to the Ansible server, could use
  this flaw to execute arbitrary code on the Ansible server using the Ansible server
  privileges."
date: "2019-10-09"
pubdate: "2018-06-22"
affected_range: "<2.3.0.0"
fixed_versions:
- "2.3.0.0"
affected_versions: "All versions before 2.3.0.0"
not_impacted: "All versions starting from 2.3.0.0"
solution: "Upgrade to version 2.3.0.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-7466"
- "http://www.securityfocus.com/bid/97595"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-7466"
cvss_v2: "AV:N/AC:M/Au:S/C:C/I:C/A:C"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H"
uuid: "4c077f14-445e-452c-a872-451f1143a32e"
cwe_ids:
- "CWE-1035"
- "CWE-20"
- "CWE-937"
identifiers:
- "CVE-2017-7466"
