---
identifier: "CVE-2020-10685"
identifiers:
- "CVE-2020-10685"
package_slug: "pypi/ansible"
title: "Exposure of Resource to Wrong Sphere"
description: "A flaw was found in Ansible when using modules which decrypts vault
  files. The temporary directory is created in `/tmp` and left unecrypted."
date: "2021-12-21"
pubdate: "2020-05-11"
affected_range: ">=2.7.0,<2.7.17||>=2.8.0,<2.8.11||>=2.9.0,<2.9.7"
fixed_versions:
- "2.7.17"
- "2.8.11"
- "2.9.7"
affected_versions: "All versions starting from 2.7.0 before 2.7.17, all versions starting
  from 2.8.0 before 2.8.11, all versions starting from 2.9.0 before 2.9.7"
not_impacted: "All versions before 2.7.0, all versions starting from 2.7.17 before
  2.8.0, all versions starting from 2.8.11 before 2.9.0, all versions starting from
  2.9.7"
solution: "Upgrade to versions 2.7.17, 2.8.11, 2.9.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-10685"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10685"
cvss_v2: "AV:L/AC:M/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "e18c911c-afd9-4ce3-9005-f71e90bd7ac4"
cwe_ids:
- "CWE-1035"
- "CWE-459"
- "CWE-937"
