---
identifier: "CVE-2019-3828"
package_slug: "pypi/ansible"
title: "Path Traversal"
description: "Ansible fetch module has a path traversal vulnerability which allows
  copying and overwriting files outside the specified destination in the local ansible
  controller host, by not restricting an absolute path."
date: "2019-04-03"
pubdate: "2019-03-27"
affected_range: ">=2.5.0,<2.5.15||>=2.6.0,<2.6.14||>=2.7.0,<2.7.8"
fixed_versions:
- "2.5.15"
- "2.6.14"
- "2.7.8"
affected_versions: "All versions starting from 2.5.0 before 2.5.15, all versions starting
  from 2.6.0 before 2.6.14, all versions starting from 2.7.0 before 2.7.8"
not_impacted: "All versions before 2.5.0, all versions starting from 2.5.15 before
  2.6.0, all versions starting from 2.6.14 before 2.7.0, all versions starting from
  2.7.8"
solution: "Upgrade to versions 2.5.15, 2.6.14, 2.7.8 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-3828"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3828"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
uuid: "8601eb86-32e7-46b0-935d-78696ff0e226"
cwe_ids:
- "CWE-1035"
- "CWE-22"
- "CWE-937"
identifiers:
- "CVE-2019-3828"
