---
identifier: "CVE-2020-14365"
package_slug: "pypi/ansible"
title: "Improper Verification of Cryptographic Signature"
description: "A flaw was found in the Ansible Engine when installing packages using
  the dnf module. GPG signatures are ignored during installation even when `disable_gpg_check`
  is set to `False`, which is the default behavior. This flaw leads to malicious packages
  being installed on the system and arbitrary code executed via package installation
  scripts. The highest threat from this vulnerability is to integrity and system availability."
date: "2021-08-07"
pubdate: "2020-09-23"
affected_range: ">=2.8.0,<=2.8.15||>=2.9.0,<=2.9.13"
fixed_versions:
- "2.8.16"
- "2.9.14"
affected_versions: "All versions starting from 2.8.0 up to 2.8.15, all versions starting
  from 2.9.0 up to 2.9.13"
not_impacted: "All versions before 2.8.0, all versions after 2.8.15 before 2.9.0,
  all versions after 2.9.13"
solution: "Upgrade to versions 2.8.16, 2.9.14 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-14365"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1869154"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:C/A:C"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H"
uuid: "5738848d-2299-44d3-9b5d-f633cf69a8ff"
cwe_ids:
- "CWE-1035"
- "CWE-347"
- "CWE-937"
identifiers:
- "CVE-2020-14365"
