---
identifier: "CVE-2018-10855"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "Ansible does not honor the `no_log` task flag for failed tasks. When
  the `no_log` flag has been used to protect sensitive data passed to a task from
  being logged, and that task does not run successfully, Ansible will expose sensitive
  data in log files and on the terminal of the user running Ansible."
date: "2019-07-25"
pubdate: "2018-07-03"
affected_range: "==2.0||>=2.4,<2.4.5||>2.5,<=2.5.5"
fixed_versions:
- "2.0.0.1"
- "2.4.5.0"
- "2.5.6"
affected_versions: "Version 2.0, all versions starting from 2.4 before 2.4.5, all
  versions after 2.5 up to 2.5.5"
not_impacted: "All versions before 2.0, all versions after 2.0 before 2.4, all versions
  starting from 2.4.5 up to 2.5, all versions after 2.5.5"
solution: "Upgrade to versions 2.0.0.1, 2.4.5.0, 2.5.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-10855"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
uuid: "bc541fd8-589a-4b40-a66e-ba4974abc749"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2018-10855"
