---
identifier: "CVE-2020-1739"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "A flaw was found in Ansible when a password is set with the argument
  `password` of svn module, it is used on svn command line, disclosing to other users
  within the same node. An attacker could take advantage by reading the cmdline file
  from that particular `PID` on the `procfs`."
date: "2021-08-07"
pubdate: "2020-03-12"
affected_range: "<=2.7.16||>=2.8.0,<=2.8.8||>=2.9.0,<=2.9.5"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions up to 2.7.16, all versions starting from 2.8.0 up
  to 2.8.8, all versions starting from 2.9.0 up to 2.9.5"
not_impacted: "All versions after 2.7.16 before 2.8.0, all versions after 2.8.8 before
  2.9.0, all versions after 2.9.5"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1739"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1739"
- "https://github.com/ansible/ansible/issues/67797"
cvss_v2: "AV:L/AC:M/Au:N/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N"
uuid: "30468e7a-32ad-42a1-afc7-ac975f09bfe8"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2020-1739"
