---
identifier: "CVE-2017-7550"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "A flaw was found in the way Ansible passed certain parameters to the
  `jenkins_plugin` module. Remote attackers could use this flaw to expose sensitive
  information from a remote host's logs."
date: "2019-10-09"
pubdate: "2017-11-21"
affected_range: ">=2.3.0,<2.3.3||>=2.4.0,<2.4.1"
fixed_versions:
- "2.3.3.0"
- "2.4.1.0"
affected_versions: "All versions starting from 2.3.0 before 2.3.3, all versions starting
  from 2.4.0 before 2.4.1"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.3 before
  2.4.0, all versions starting from 2.4.1"
solution: "Upgrade to versions 2.3.3.0, 2.4.1.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-7550"
- "https://access.redhat.com/errata/RHSA-2017:2966"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1473645"
- "https://github.com/ansible/ansible/issues/30874"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "6d86d051-fc8f-4d78-993d-e282d907da43"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2017-7550"
