---
identifier: "CVE-2014-4657"
package_slug: "pypi/ansible"
title: "Security fix for safe_eval"
description: "The `safe_eval` function in Ansible does not properly restrict the code
  subset, which allows remote attackers to execute arbitrary code via crafted instructions."
date: "2020-02-25"
pubdate: "2020-02-20"
affected_range: "<1.5.4"
fixed_versions:
- "1.5.4"
affected_versions: "All versions before 1.5.4"
not_impacted: "All versions starting from 1.5.4"
solution: "Upgrade to version 1.5.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2014-4657"
- "https://www.securityfocus.com/bid/68232"
- "https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md"
- "https://github.com/ansible/ansible/commit/998793fd0ab55705d57527a38cee5e83f535974c"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "2621a7ea-3b51-44e9-8cc1-5d3ec5aae5d5"
cwe_ids:
- "CWE-1035"
- "CWE-20"
- "CWE-937"
identifiers:
- "CVE-2014-4657"
