---
identifier: "CVE-2021-3583"
identifiers:
- "CVE-2021-3583"
package_slug: "pypi/ansible"
title: "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
description: "A flaw was found in Ansible, where a user's controller is vulnerable
  to template injection. This issue can occur through facts used in the template if
  the user is trying to put templates in multi-line YAML strings and the facts being
  handled do not routinely include special template characters. This flaw allows attackers
  to perform command injection, which discloses sensitive information. The highest
  threat from this vulnerability is to confidentiality and integrity."
date: "2023-12-28"
pubdate: "2021-09-22"
affected_range: "<2.9.23"
fixed_versions:
- "2.9.23"
affected_versions: "All versions before 2.9.23"
not_impacted: "All versions starting from 2.9.23"
solution: "Upgrade to version 2.9.23 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3583"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1968412"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"
uuid: "aeb19c98-a6f4-4b3b-aa59-e9fdb157cea1"
cwe_ids:
- "CWE-1035"
- "CWE-937"
- "CWE-94"
