---
identifier: "CVE-2019-10217"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "Fields managing sensitive data should be set as such by no_log feature.
  Some of these fields in GCP modules are not set properly. `service_account_contents()`
  which is common class for all gcp modules is not setting `no_log` to `True`. Any
  sensitive data managed by that function would be leaked as an output when running
  ansible playbooks."
date: "2019-12-11"
pubdate: "2019-11-25"
affected_range: ">=2.8.0,<2.8.4"
fixed_versions:
- "2.8.4"
affected_versions: "All versions starting from 2.8.0 before 2.8.4"
not_impacted: "All versions before 2.8.0, all versions starting from 2.8.4"
solution: "Upgrade to version 2.8.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-10217"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10217"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "ba78579b-a96f-4ceb-9eb0-0cf6a4b034ae"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2019-10217"
