---
identifier: "CVE-2016-8647"
package_slug: "pypi/ansible"
title: "Improper Input Validation"
description: "An input validation vulnerability was found in Ansible's `mysql_user`
  module, which may fail to correctly change a password in certain circumstances.
  Thus, the previous password would still be active when it should have been changed."
date: "2019-10-09"
pubdate: "2018-07-26"
affected_range: "<2.2.1.0"
fixed_versions:
- "2.2.1.0"
affected_versions: "All versions before 2.2.1.0"
not_impacted: "All versions starting from 2.2.1.0"
solution: "Upgrade to version 2.2.1.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2016-8647"
- "https://access.redhat.com/errata/RHSA-2017:1685"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:P/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:N"
uuid: "c227f0f7-e770-4f7a-b18a-aba2bb11162d"
cwe_ids:
- "CWE-1035"
- "CWE-20"
- "CWE-937"
identifiers:
- "CVE-2016-8647"
