---
identifier: "CVE-2020-10729"
identifiers:
- "CVE-2020-10729"
package_slug: "pypi/ansible"
title: "Use of Insufficiently Random Values"
description: "A flaw was found in the use of insufficiently random values in Ansible.
  Two random password lookups of the same length generate the equal value as the template
  caching action for the same file since no re-evaluation happens. The highest threat
  from this vulnerability would be that all passwords are exposed at once for the
  file."
date: "2021-12-10"
pubdate: "2021-05-27"
affected_range: "<2.9.6"
fixed_versions:
- "2.9.6"
affected_versions: "All versions before 2.9.6"
not_impacted: "All versions starting from 2.9.6"
solution: "Upgrade to version 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-10729"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1831089"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "51f67a79-25df-4bc3-810d-671ff8ccdaf4"
cwe_ids:
- "CWE-1035"
- "CWE-330"
- "CWE-937"
