---
identifier: "CVE-2014-2686"
package_slug: "pypi/ansible"
title: "Always-Incorrect Control Flow Implementation"
description: "Ansible mishandles the evaluation of some strings."
date: "2020-01-21"
pubdate: "2020-01-09"
affected_range: "<1.5.4"
fixed_versions:
- "1.5.4"
affected_versions: "All versions before 1.5.4"
not_impacted: "All versions starting from 1.5.4"
solution: "Upgrade to version 1.5.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2014-2686"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
uuid: "dc14397e-eb3e-4b16-b80d-8b28aed7d89a"
cwe_ids:
- "CWE-1035"
- "CWE-670"
- "CWE-937"
identifiers:
- "CVE-2014-2686"
