---
identifier: "CVE-2020-20178"
package_slug: "pypi/ansible"
title: "Reachable Assertion"
description: "A flaw was found in OpenLDAP. This flaw allows an attacker who can send
  a malicious packet to be processed by OpenLDAPâ€™s slapd server, to trigger an assertion
  failure. The highest threat from this vulnerability is to system availability."
date: "2021-05-28"
pubdate: "2021-05-24"
affected_range: "<2.9.18"
fixed_versions:
- "2.9.18"
affected_versions: "All versions before 2.9.18"
not_impacted: "All versions starting from 2.9.18"
solution: "Upgrade to version 2.9.18 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-20178"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1914774"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "a84b5b02-281e-41da-bd5a-2b81568f767f"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2020-20178"
