---
identifier: "CVE-2021-3447"
identifiers:
- "CVE-2021-3447"
package_slug: "pypi/ansible"
title: "Inclusion of Sensitive Information in Log Files"
description: "A flaw was found in several ansible modules, where parameters containing
  credentials, such as secrets, were being logged in plain-text on managed nodes,
  as well as being made visible on the controller node when run in verbose mode. These
  parameters were not protected by the `no_log` feature. An attacker can take advantage
  of this information to steal those credentials, provided when they have access to
  the log files containing them. The highest threat from this vulnerability is to
  data confidentiality. This flaw affects Red Hat Ansible Automation Platform and
  Ansible Tower "
date: "2023-12-28"
pubdate: "2021-04-01"
affected_range: "<1.2.2"
fixed_versions:
- "1.2.2"
affected_versions: "All versions before 1.2.2"
not_impacted: "All versions starting from 1.2.2"
solution: "Upgrade to version 1.2.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3447"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1939349"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "4fafb194-e8b3-405f-94ab-427d297ab641"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
