---
identifier: "CVE-2018-16837"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "The ansible 'User' module leaks any data which is passed on as a parameter
  to ssh-keygen. This could lean in undesirable situations such as passphrases credentials
  passed as a parameter for the `ssh-keygen` executable. Showing those credentials
  in clear text form for every user which have access just to the process list."
date: "2019-10-03"
pubdate: "2018-10-23"
affected_range: "==2.0||>=2.5,<=2.7"
fixed_versions:
- "2.0.0.1"
- "2.7.1"
affected_versions: "Version 2.0, all versions starting from 2.5 up to 2.7"
not_impacted: "All versions before 2.0, all versions after 2.0 before 2.5, all versions
  after 2.7"
solution: "Upgrade to versions 2.0.0.1, 2.7.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-16837"
- "http://www.securityfocus.com/bid/105700"
- "https://github.com/ansible/ansible/blob/stable-2.5/changelogs/CHANGELOG-v2.5.rst#v2511"
- "https://github.com/ansible/ansible/blob/stable-2.6/changelogs/CHANGELOG-v2.6.rst#v267"
- "https://github.com/ansible/ansible/blob/stable-2.7/changelogs/CHANGELOG-v2.7.rst#v2-7-1"
- "https://github.com/ansible/ansible/commit/a0aa53d1a1d6075a7ae98ace138712ee6cb45ae4"
- "https://github.com/ansible/ansible/pull/47436"
credit: "Markus Teufelberger"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "74a50c30-7dd0-4f2e-a44c-422fb3b274ee"
cwe_ids:
- "CWE-1035"
- "CWE-311"
- "CWE-937"
identifiers:
- "CVE-2018-16837"
