---
identifier: "CVE-2021-3620"
identifiers:
- "CVE-2021-3620"
package_slug: "pypi/ansible"
title: "Generation of Error Message Containing Sensitive Information"
description: "A flaw was found in Ansible Engine's ansible-connection module, where
  sensitive information such as the Ansible user credentials is disclosed by default
  in the traceback error message. The highest threat from this vulnerability is to
  confidentiality."
date: "2023-12-28"
pubdate: "2022-03-03"
affected_range: "<2.9.27"
fixed_versions:
- "2.9.27"
affected_versions: "All versions before 2.9.27"
not_impacted: "All versions starting from 2.9.27"
solution: "Upgrade to version 2.9.27 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3620"
- "https://github.com/ansible/ansible/commit/fe28767970c8ec62aabe493c46b53a5de1e5fac0"
- "https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#security-fixes"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1975767"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "7ed6d263-a35a-4c59-b98b-13790da6eeb6"
cwe_ids:
- "CWE-1035"
- "CWE-209"
- "CWE-937"
