---
identifier: "CVE-2021-3533"
identifiers:
- "CVE-2021-3533"
package_slug: "pypi/ansible"
title: "Time-of-check Time-of-use (TOCTOU) Race Condition"
description: "A flaw was found in Ansible if an ansible user sets ANSIBLE_ASYNC_DIR
  to a subdirectory of a world writable directory. When this occurs, there is a race
  condition on the managed machine. A malicious, non-privileged account on the remote
  machine can exploit the race condition to access the async result data. This flaw
  affects Ansible Tower and Ansible Automation Platform "
date: "2022-04-25"
pubdate: "2021-06-09"
affected_range: "==2.0"
fixed_versions:
- "2.0.0.1"
affected_versions: "Version 2.0"
not_impacted: "All versions before 2.0, all versions after 2.0"
solution: "Upgrade to version 2.0.0.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-3533"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1956477"
cvss_v2: "AV:L/AC:H/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N"
uuid: "16d1c687-3fd1-4afa-98a0-d325dd622407"
cwe_ids:
- "CWE-1035"
- "CWE-362"
- "CWE-937"
