---
identifier: "CVE-2020-25635"
identifiers:
- "CVE-2020-25635"
- "GHSA-f556-49jc-4rvc"
package_slug: "pypi/ansible"
title: "Ansible does not collect garbage after playbook run"
description: "A flaw was found in Ansible Base when using the aws_ssm connection plugin
  as its garbage collector is not happening after the playbook run is completed. Files
  would remain in the bucket exposing the data. This issue directly affects data confidentiality."
date: "2025-10-31"
pubdate: "2025-10-31"
affected_range: "<2.10.1"
fixed_versions:
- "2.10.1"
affected_versions: "All versions before 2.10.1"
not_impacted: "All versions starting from 2.10.1"
solution: "Upgrade to version 2.10.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-25635"
- "https://github.com/advisories/GHSA-f556-49jc-4rvc"
- "https://github.com/ansible-collections/community.aws/issues/222"
- "https://github.com/ansible-collections/community.aws/pull/237#issuecomment-1468591094"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635"
- "https://github.com/ansible/ansible"
- "https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2020-220.yaml"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "a4ed6a72-3ad0-4a01-b14f-8404f36467d7"
cwe_ids:
- "CWE-212"
- "CWE-937"
- "CWE-1035"
