---
identifier: "CVE-2020-1740"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "A flaw was found in Ansible Engine when using Ansible Vault for editing
  encrypted files. When a user executes `ansible-vault edit`, another user on the
  same computer can read the old and new secret, as it is created in a temporary file
  with mkstemp and the returned file descriptor is closed and the method write_data
  is called to write the existing secret in the file. This method will delete the
  file before recreating it insecurely."
date: "2021-08-07"
pubdate: "2020-03-16"
affected_range: "<=2.7.16||>=2.8.0,<=2.8.8||>=2.9.0,<=2.9.5"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions up to 2.7.16, all versions starting from 2.8.0 up
  to 2.8.8, all versions starting from 2.9.0 up to 2.9.5"
not_impacted: "All versions after 2.7.16 before 2.8.0, all versions after 2.8.8 before
  2.9.0, all versions after 2.9.5"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1740"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1740"
cvss_v2: "AV:L/AC:M/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "83300929-1e97-49ef-99f8-87abb761b8ea"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2020-1740"
