---
identifier: "CVE-2021-20180"
identifiers:
- "CVE-2021-20180"
package_slug: "pypi/ansible"
title: "Insertion of Sensitive Information into Log File"
description: "A flaw was found in ansible module where credentials are disclosed in
  the console log by default and not protected by the security feature when using
  the bitbucket_pipeline_variable module. This flaw allows an attacker to steal bitbucket_pipeline
  credentials. The highest threat from this vulnerability is to confidentiality."
date: "2022-03-22"
pubdate: "2022-03-16"
affected_range: "<2.9.18"
fixed_versions:
- "2.9.18"
affected_versions: "All versions before 2.9.18"
not_impacted: "All versions starting from 2.9.18"
solution: "Upgrade to version 2.9.18 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-20180"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1915808"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "7921bf61-f7d0-432a-bc44-3bb89ca89a9e"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
