---
identifier: "CVE-2020-25636"
package_slug: "pypi/ansible"
title: "Files or Directories Accessible to External Parties"
description: "A flaw was found in Ansible Base when using the `aws_ssm` connection
  plugin as there is no namespace separation for file transfers. Files are written
  directly to the root bucket, making possible to have collisions when running multiple
  ansible processes. This issue affects mainly the service availability."
date: "2020-10-09"
pubdate: "2020-10-05"
affected_range: "==2.10.1"
fixed_versions: []
affected_versions: "Version 2.10.1"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-25636"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25636"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H"
uuid: "7d14dd49-2aaf-4894-96c8-4b9b0752aa56"
cwe_ids:
- "CWE-1035"
- "CWE-552"
- "CWE-937"
identifiers:
- "CVE-2020-25636"
