---
identifier: "CVE-2025-14010"
identifiers:
- "CVE-2025-14010"
- "GHSA-8ggh-xwr9-3373"
package_slug: "pypi/ansible"
title: "Ansible Community General Collection is vulnerable to exposure of sensitive
  information"
description: "A flaw was found in ansible-collection-community-general. This vulnerability
  allows for information exposure (IE) of sensitive credentials, specifically plaintext
  passwords, via verbose output when running Ansible with debug modes. Attackers with
  access to logs could retrieve these secrets and potentially compromise Keycloak
  accounts or administrative access."
date: "2025-12-05"
pubdate: "2025-12-04"
affected_range: "<12.0.0"
fixed_versions:
- "12.0.0"
affected_versions: "All versions before 12.0.0"
not_impacted: "All versions starting from 12.0.0"
solution: "Upgrade to version 12.0.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-14010"
- "https://github.com/advisories/GHSA-8ggh-xwr9-3373"
- "https://github.com/ansible-collections/community.general/pull/11005"
- "https://github.com/ansible-collections/community.general/commit/54af64ad363efe280b34102d2637fe272c1f7320"
- "https://access.redhat.com/security/cve/CVE-2025-14010"
- "https://bugzilla.redhat.com/show_bug.cgi?id=2418774"
- "https://github.com/ansible-collections/community.general"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "7c01b9bb-0314-4821-948d-310cf3b00517"
cwe_ids:
- "CWE-200"
- "CWE-937"
- "CWE-1035"
