---
identifier: "CVE-2020-1738"
package_slug: "pypi/ansible"
title: "Argument Injection or Modification"
description: "A flaw was found in Ansible Engine when the module package or service
  is used and the parameter `use` is not specified. If a previous task is executed
  with a malicious user, the module sent can be selected by the attacker using the
  ansible facts file."
date: "2021-08-04"
pubdate: "2020-03-16"
affected_range: "<=2.7.16||>=2.8.0,<=2.8.8||>=2.9.0,<=2.9.5"
fixed_versions:
- "2.7.17"
- "2.8.9"
- "2.9.6"
affected_versions: "All versions up to 2.7.16, all versions starting from 2.8.0 up
  to 2.8.8, all versions starting from 2.9.0 up to 2.9.5"
not_impacted: "All versions after 2.7.16 before 2.8.0, all versions after 2.8.8 before
  2.9.0, all versions after 2.9.5"
solution: "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1738"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1738"
cvss_v2: "AV:L/AC:H/Au:N/C:N/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:C/C:N/I:L/A:L"
uuid: "e47a715f-5261-46ea-b996-af27cb8540a3"
cwe_ids:
- "CWE-1035"
- "CWE-88"
- "CWE-937"
identifiers:
- "CVE-2020-1738"
