---
identifier: "CVE-2020-1746"
package_slug: "pypi/ansible"
title: "Information Exposure"
description: "A flaw was found in the Ansible when the `ldap_attr` and `ldap_entry`
  community modules are used. The issue discloses the LDAP bind password to stdout
  or a log file if a playbook task is written using the `bind_pw` in the parameters
  field. The highest threat from this vulnerability is data confidentiality."
date: "2021-10-19"
pubdate: "2020-05-12"
affected_range: ">=2.7.0,<2.7.17||>=2.8.0,<2.8.11||>=2.9.0,<2.9.7"
fixed_versions:
- "2.7.17"
- "2.8.11"
- "2.9.7"
affected_versions: "All versions starting from 2.7.0 before 2.7.17, all versions starting
  from 2.8.0 before 2.8.11, all versions starting from 2.9.0 before 2.9.7"
not_impacted: "All versions before 2.7.0, all versions starting from 2.7.17 before
  2.8.0, all versions starting from 2.8.11 before 2.9.0, all versions starting from
  2.9.7"
solution: "Upgrade to versions 2.7.17, 2.8.11, 2.9.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-1746"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1746"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
cvss_v2: "AV:L/AC:M/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N"
uuid: "7a52a3d0-eb62-4c43-b53e-1bfa34e95dfc"
identifiers:
- "CVE-2020-1746"
