---
identifier: "CVE-2017-1000113"
package_slug: "maven/org.jenkins-ci.plugins/deploy"
title: "Information Exposure"
description: "This plugin stores passwords unencrypted as part of its configuration.
  This allowed users with Jenkins master local file system access, or users with Extended
  Read access to the jobs it is used in, to retrieve those passwords."
date: "2019-06-11"
pubdate: "2017-10-05"
affected_range: "(,1.12]"
fixed_versions:
- "1.13"
affected_versions: "All versions up to 1.12"
not_impacted: "All versions after 1.12"
solution: "Upgrade to version 1.13 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-1000113"
- "https://jenkins.io/security/advisory/2017-08-07/"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "72e22766-c101-447e-a963-005ec1e84b95"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2017-1000113"
