---
identifier: "CVE-2020-8552"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "Allocation of Resources Without Limits or Throttling"
description: "The Kubernetes API server component has been found to be vulnerable
  to a denial of service attack via successful API requests."
date: "2020-07-24"
pubdate: "2020-03-27"
affected_range: "<=v1.15.9 || >=v1.16.0 <=v1.16.6 || >=v1.17.0 <=v1.17.2"
fixed_versions:
- "v1.17.3"
- "v1.16.7"
- "v1.15.10"
affected_versions: "All versions up to 1.15.9, all versions starting from 1.16.0 up
  to 1.16.6, all versions starting from 1.17.0 up to 1.17.2"
not_impacted: "All versions starting from v1.15.10 before v1.16.0, all versions starting
  from v1.16.7 before v1.17.0, all versions after v1.17.3"
solution: "Upgrade to versions v1.15.10, v1.16.7, v1.17.3 or above"
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8552"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
uuid: "f13da45d-ff8b-4342-9b80-dca6764faba6"
versions:
- number: "v1.16.0"
  commit:
    tags:
    - "v1.16.0"
    sha: "38d05c7c415152c9249ad0c553cbbcb86f247a68"
    timestamp: "20190913165653"
- number: "v1.17.0"
  commit:
    tags:
    - "v1.17.0"
    sha: "02a9c9f39a18ee40c37835c36c7c80e0797b0d85"
    timestamp: "20191206022503"
- number: "v1.16.6"
  commit:
    tags:
    - "v1.16.6"
    sha: "41e842ae7c549f18c093acdd69afdf05bb203abb"
    timestamp: "20200118001809"
- number: "v1.15.9"
  commit:
    tags:
    - "v1.15.9"
    sha: "d95829605534897dcb2c2824c6ee332399716e86"
    timestamp: "20200118002609"
- number: "v1.17.2"
  commit:
    tags:
    - "v1.17.2"
    sha: "9b951899e55cb99cc9bb68a11fc0051c737f1903"
    timestamp: "20200118011809"
cwe_ids:
- "CWE-1035"
- "CWE-770"
- "CWE-937"
identifiers:
- "CVE-2020-8552"
