---
identifier: "CVE-2020-8565"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "Inclusion of Sensitive Information in Log Files"
description: "In Kubernetes, if the logging level is set to at least 9, authorization
  and bearer tokens will be written to log files."
date: "2020-12-08"
pubdate: "2020-12-07"
affected_range: ">=v1.17.0 <=v1.17.13 || >=v1.18.0 <=v1.18.10 || >=v1.19.0 <=v1.19.3"
fixed_versions:
- "v1.17.14-rc.0"
- "v1.18.11-rc.0"
- "v1.19.4-rc.0"
affected_versions: "All versions starting from 1.17.0 up to 1.17.13, all versions
  starting from 1.18.0 up to 1.18.10, all versions starting from 1.19.0 up to 1.19.3"
not_impacted: "All versions before 1.17.0, all versions after 1.17.13 before 1.18.0,
  all versions after 1.18.10 before 1.19.0, all versions after 1.19.3"
solution: "Upgrade to versions 1.17.14-rc.0, 1.18.11-rc.0, 1.19.4-rc.0 or above. *Note*:
  1.17.14-rc.0, 1.18.11-rc.0, and 1.19.4-rc.0 may be unstable versions. Use caution."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8565"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "47a4ccf2-1175-4739-b9b6-d2af792fd7ce"
versions:
- number: "v1.17.0"
  commit:
    tags:
    - "v1.17.0"
    sha: "02a9c9f39a18ee40c37835c36c7c80e0797b0d85"
    timestamp: "20191206012503"
- number: "v1.18.0"
  commit:
    tags:
    - "v1.18.0"
    sha: "f6cc41b23ef90243e9dbba5fbad501630caaa737"
    timestamp: "20200325144952"
- number: "v1.19.0"
  commit:
    tags:
    - "v1.19.0"
    sha: "0fc1dcd829d621ec5605d3eeb381e728371da832"
    timestamp: "20200826142205"
- number: "v1.19.4-rc.0"
  commit:
    tags:
    - "v1.19.4-rc.0"
    sha: "f8f9da017bafd927ba0e1046572a914e3341a42f"
    timestamp: "20201014123937"
- number: "v1.19.3"
  commit:
    tags:
    - "v1.19.3"
    sha: "c3dc35c4e9145c1b9f6b2f14545b3d76ca1e0a3b"
    timestamp: "20201014123937"
- number: "v1.17.13"
  commit:
    tags:
    - "v1.17.13"
    sha: "8103ff82e083f536b3a6cdfdb1f8621cc827981a"
    timestamp: "20201015005831"
- number: "v1.17.14-rc.0"
  commit:
    tags:
    - "v1.17.14-rc.0"
    sha: "3ab59c453ca5a23325330317856061a11059be47"
    timestamp: "20201015005832"
- number: "v1.18.10"
  commit:
    tags:
    - "v1.18.10"
    sha: "1eaa7b6516ecf87a518a94f95e260487db272b88"
    timestamp: "20201015014302"
- number: "v1.18.11-rc.0"
  commit:
    tags:
    - "v1.18.11-rc.0"
    sha: "5a35729e05e1bcf398d82b3c97f24ad925f9f8d7"
    timestamp: "20201015014303"
cwe_ids:
- "CWE-1035"
- "CWE-532"
- "CWE-937"
identifiers:
- "CVE-2020-8565"
