---
identifier: "CVE-2017-1002102"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "Path Traversal"
description: "In Kubernetes containers using a secret, configMap, projected or downwardAPI
  volume can trigger deletion of arbitrary files and directories from the nodes where
  they are running."
date: "2019-10-09"
pubdate: "2018-03-13"
affected_range: ">=v1.3.0 <=v1.3.10 || >=v1.4.0 <=v1.4.12 || >=v1.5.0 <=v1.5.8 ||
  >=v1.6.0 <=v1.6.13 || >=v1.7.0 <v1.7.14 || >=v1.8.0 <v1.8.9 || >=v1.9.0 <v1.9.4"
fixed_versions:
- "v1.3.11"
- "v1.5.9"
- "v1.6.14"
- "v1.7.14"
- "v1.8.9"
- "v1.9.4"
affected_versions: "All versions starting from 1.3.0 up to 1.3.10, all versions starting
  from 1.4.0 up to 1.4.12, all versions starting from 1.5.0 up to 1.5.8, all versions
  starting from 1.6.0 up to 1.6.13, all versions starting from 1.7.0 before 1.7.14,
  all versions starting from 1.8.0 before 1.8.9, all versions starting from 1.9.0
  before 1.9.4"
not_impacted: "All versions before 1.3.0, all versions after 1.3.10 before 1.4.0,
  all versions after 1.4.12 before 1.5.0, all versions after 1.5.8 before 1.6.0, all
  versions after 1.6.13 before 1.7.0, all versions starting from 1.7.14 before 1.8.0,
  all versions starting from 1.8.9 before 1.9.0, all versions starting from 1.9.4"
solution: "Upgrade to versions 1.3.11, 1.5.0, 1.5.9, 1.6.14, 1.7.14, 1.8.9, 1.9.4
  or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-1002102"
- "https://github.com/kubernetes/kubernetes/issues/60814"
cvss_v2: "AV:L/AC:M/Au:N/C:N/I:C/A:C"
cvss_v3: "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:C/C:N/I:H/A:N"
uuid: "b55cea81-cda0-458f-9eaa-660b1b6697f1"
versions:
- number: "v1.3.0"
  commit:
    tags:
    - "v1.3.0"
    sha: "346bcde207a77e555fa87fe3de4262ee1f9e24bf"
    timestamp: "20160701211906"
- number: "v1.4.0"
  commit:
    tags:
    - "v1.4.0"
    sha: "1b38de6a9dbcd8c4f613449e4fcf190d36751682"
    timestamp: "20160926200947"
- number: "v1.3.10"
  commit:
    tags:
    - "v1.3.10"
    sha: "c46df74c5df2b59ac99a39ee29e0949926b2a466"
    timestamp: "20161031220611"
- number: "v1.3.11"
  commit:
    tags:
    - "v1.3.11-beta.0"
    sha: "86f65a0933ad97533eacf371fabc8d666229dd57"
    timestamp: "20161031224214"
- number: "v1.5.0"
  commit:
    tags:
    - "v1.5.0"
    sha: "c7761bada49581ee1813737764c007d3e6a405b0"
    timestamp: "20161213002943"
- number: "v1.6.0"
  commit:
    tags:
    - "v1.6.0"
    sha: "7ee608dd786340302239f687b4dbe291ee78b5f3"
    timestamp: "20170328182306"
- number: "v1.4.12"
  commit:
    tags:
    - "v1.4.12"
    sha: "ed8752f8e505bc5c0a06bd67f1bcd9759ab718e3"
    timestamp: "20170420225346"
- number: "v1.7.0"
  commit:
    tags:
    - "v1.7.0"
    sha: "b6928f788afa6663acedb0dcfee3dcf0e16ece70"
    timestamp: "20170630005316"
- number: "v1.8.0"
  commit:
    tags:
    - "v1.8.0"
    sha: "36393a268be8e17af666236269f9c44959d8d716"
    timestamp: "20170929001357"
- number: "v1.5.8"
  commit:
    tags:
    - "v1.5.8"
    sha: "e78e52036b845abe70bec42392c8ec588292521a"
    timestamp: "20171001015957"
- number: "v1.5.9"
  commit:
    tags:
    - "v1.5.9-beta.0"
    sha: "6b83a45d5cfe959518f000efc207db9619c34071"
    timestamp: "20171001030940"
- number: "v1.6.13"
  commit:
    tags:
    - "v1.6.13"
    sha: "2f8d9f9bae634c34b5f9e002d78f350a50650655"
    timestamp: "20171118002643"
- number: "v1.6.14"
  commit:
    tags:
    - "v1.6.14-beta.0"
    sha: "fd84a0b721a56c090bcd7d4b06f44645709955ac"
    timestamp: "20171122221405"
- number: "v1.9.0"
  commit:
    tags:
    - "v1.9.0"
    sha: "65bb45a3ea941924154f24a08a1462d5ff084121"
    timestamp: "20171214202037"
- number: "v1.9.4"
  commit:
    tags:
    - "v1.9.4"
    sha: "5cdc7fc16d431c7ac1e0cae13330e05ac8e97a41"
    timestamp: "20180312170313"
- number: "v1.8.9"
  commit:
    tags:
    - "v1.8.9"
    sha: "b12ed27fcb9bad9f7438af9c7855d27dd1d9d2fb"
    timestamp: "20180312170558"
- number: "v1.7.14"
  commit:
    tags:
    - "v1.7.14"
    sha: "962389e2049bfffd0447fb60346df471bc9863f2"
    timestamp: "20180312170713"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2017-1002102"
