---
identifier: "CVE-2017-1002100"
package_slug: "go/github.com/kubernetes/kubernetes"
title: "Information Exposure"
description: "Default access permissions for Persistent Volumes (PVs) created by the
  Kubernetes Azure cloud provider are set to \"container\" which exposes a URI that
  can be accessed without authentication on the public internet. Access to the URI
  string requires privileged access to the Kubernetes cluster or authenticated access
  to the Azure portal."
date: "2017-09-29"
pubdate: "2017-09-14"
affected_range: ">=v1.6.0 <=v1.6.5"
fixed_versions:
- "v1.6.6"
affected_versions: "All versions starting from 1.6.0 up to 1.6.5"
not_impacted: "All versions before 1.6.0, all versions after 1.6.5"
solution: "Upgrade to version 1.6.6-beta.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-1002100"
- "https://github.com/kubernetes/kubernetes/issues/47611"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "51d34fb9-ea0f-4248-b014-9a12c519a78a"
versions:
- number: "v1.6.0"
  commit:
    tags:
    - "v1.6.0"
    sha: "7ee608dd786340302239f687b4dbe291ee78b5f3"
    timestamp: "20170328182306"
- number: "v1.6.5"
  commit:
    tags:
    - "v1.6.5"
    sha: "4d0a64d2706bba688dd53f8ec80319c132847044"
    timestamp: "20170614220153"
- number: "v1.6.6-beta.0"
  commit:
    tags:
    - "v1.6.6"
    sha: "36ffcbfdadbb0d72037da0d9ab9d60379160937f"
    timestamp: "20170614230109"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2017-1002100"
