---
identifier: "CVE-2021-41092"
identifiers:
- "CVE-2021-41092"
- "GHSA-99pg-grm5-qq3v"
package_slug: "go/github.com/docker/cli"
title: "Exposure of Sensitive Information to an Unauthorized Actor"
description: "Docker CLI is the command line interface for the docker container runtime.
  Users should update to this version as soon as possible. For users unable to update
  ensure that any configured `credsStore` or `credHelpers` entries in the configuration
  file reference an installed credential helper that is executable and on the PATH."
date: "2023-11-07"
pubdate: "2021-10-04"
affected_range: "<v20.10.9"
fixed_versions:
- "v20.10.9"
affected_versions: "All versions before 20.10.9"
not_impacted: ""
solution: "Upgrade to version 20.10.9 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-41092"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
uuid: "ef01633b-6ca6-4016-81fb-5a55a64590aa"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
versions:
- number: "v20.10.9"
  commit:
    tags:
    - "v20.10.9"
    sha: "6ed7fbd180d85093f9567e43d1e6529a0e8cab15"
    timestamp: "20210923182634"
