---
identifier: "CVE-2019-1002101"
package_slug: "go/github.com/kubernetes/client-go"
title: "Improper Link Resolution Before File Access"
description: "The kubectl `cp` command allows copying files between containers and
  the user machine. To copy files from a container, Kubernetes creates a tar inside
  the container, copies it over the network, and kubectl unpacks it on the user's
  machine. If the tar binary in the container is malicious, it could run any code
  and output unexpected, malicious results. An attacker could use this to write files
  to any path on the user's machine when kubectl `cp` is called, limited only by the
  system permissions of the local user. The `untar` function can both create and follow
  symbolic links."
date: "2019-10-22"
pubdate: "2019-04-01"
affected_range: ">=v1.11.0 <v1.11.9 || >=v1.12.0 <v1.12.7 || >=v1.13.0 <v1.13.5 ||
  =v1.14.0"
fixed_versions:
- "v1.14.1"
affected_versions: "All versions starting from 1.11.0 before 1.11.9, all versions
  starting from 1.12.0 before 1.12.7, all versions starting from 1.13.0 before 1.13.5,
  version 1.14.0"
_git_import_path: "go/github.com/kubernetes/client-go/discovery/cached/disk"
not_impacted: "All versions before 1.11.0, all versions starting from 1.11.9 before
  1.12.0, all versions starting from 1.12.7 before 1.13.0, all versions starting from
  1.13.5 before 1.14.0, all versions after 1.14.0"
solution: "Upgrade to version kubernetes-1.16.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-1002101"
- "http://www.securityfocus.com/bid/107652"
cvss_v2: "AV:N/AC:M/Au:N/C:N/I:P/A:P"
uuid: "5a90e146-6740-4f3d-b256-f2e583c12822"
versions:
- number: "v1.11.0"
  commit:
    tags:
    - "kubernetes-1.11.0"
    sha: "7a66677755f880f16034b3785c75f4b21bfa9ed9"
    timestamp: "20180628063050"
- number: "v1.12.0"
  commit:
    tags:
    - "kubernetes-1.12.0"
    sha: "abcb3a804c4b8d680921d3d4cc5dda6aa8df9995"
    timestamp: "20181004144242"
- number: "v1.13.0"
  commit:
    tags:
    - "kubernetes-1.13.0"
    sha: "c1f6f3b37bf498dd1de36cdb374019fe258a835e"
    timestamp: "20181204010744"
- number: "v1.13.5"
  commit:
    tags:
    - "kubernetes-1.13.5"
    sha: "88a0b773c8d38fb242e0401847bb36c673aa21ed"
    timestamp: "20190307171346"
- number: "v1.14.0"
  commit:
    tags:
    - "kubernetes-1.14.0"
    sha: "0aa5eab985ac602d9911b5dae9fc82c778f0bf7a"
    timestamp: "20190314005726"
- number: "v1.12.7"
  commit:
    tags:
    - "kubernetes-1.12.7"
    sha: "28b8198e1cd15cd717798754e106063f7b41e619"
    timestamp: "20190325155348"
- number: "v1.11.9"
  commit:
    tags:
    - "kubernetes-1.11.9"
    sha: "8306de303f6f137ac04b881f0fe6cd94ef6dc34b"
    timestamp: "20190325195812"
- number: "v1.14.1"
  commit:
    tags:
    - "kubernetes-1.14.1"
    sha: "39bdd41acd22264d8c791bf01cd7c85281f13b4d"
    timestamp: "20190409041438"
cwe_ids:
- "CWE-1035"
- "CWE-59"
- "CWE-937"
identifiers:
- "CVE-2019-1002101"
