---
identifier: "CVE-2020-13250"
package_slug: "go/github.com/hashicorp/consul/config"
title: "Improper Restriction of Operations within the Bounds of a Memory Buffer"
description: "HashiCorp Consul and Consul Enterprise include an HTTP API caching feature
  that was vulnerable to denial of service."
date: "2020-06-17"
pubdate: "2020-06-11"
affected_range: ">=v1.2.0 <v1.6.6 || >=v1.7.0 <v1.7.4"
fixed_versions:
- "v1.6.6"
- "v1.7.4"
affected_versions: "All versions starting from 1.2.0 before 1.6.6, all versions starting
  from 1.7.0 before 1.7.4"
not_impacted: "All versions before 1.2.0, all versions starting from 1.6.6 before
  1.7.0, all versions starting from 1.7.4"
solution: "Upgrade to versions 1.6.6, 1.7.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-13250"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "0de93817-4d3d-47a3-884d-138779c9f372"
versions:
- number: "v1.2.0"
  commit:
    tags:
    - "v1.2.0"
    sha: "7019d92a4dccea1c0d74b711cb07169c03b32726"
    timestamp: "20180625214520"
- number: "v1.7.0"
  commit:
    tags:
    - "v1.7.0"
    sha: "2d3254aff41bc4bac5423d2d4b675b62d3283354"
    timestamp: "20200211161916"
- number: "v1.7.4"
  commit:
    tags:
    - "v1.7.4"
    sha: "f5eafca188f09a95d3222233cb6a9c56277b1094"
    timestamp: "20200610220330"
- number: "v1.6.6"
  commit:
    tags:
    - "v1.6.6"
    sha: "0e7c95f88a3abc31f3c9219e5dfa54cb546649ce"
    timestamp: "20200610231631"
cwe_ids:
- "CWE-1035"
- "CWE-119"
- "CWE-937"
identifiers:
- "CVE-2020-13250"
