---
identifier: "CVE-2020-8557"
package_slug: "go/github.com/kubernetes/kubelet"
title: "Uncontrolled Resource Consumption"
description: "The `/etc/hosts` file mounted in a pod by kubelet is not included by
  the kubelet eviction manager when calculating ephemeral storage usage by a pod.
  If a pod writes a large amount of data to the `/etc/hosts` file, it could fill the
  storage space of the node and cause the node to fail."
date: "2020-08-21"
pubdate: "2020-07-23"
affected_range: "<v1.16.13 || >=v1.17.0 <v1.17.9 || >=v1.18.0 <v1.18.6"
fixed_versions:
- "v1.16.13"
- "v1.17.9"
- "v1.18.6"
affected_versions: "All versions before 1.16.13, all versions starting from 1.17.0
  before 1.17.9, all versions starting from 1.18.0 before 1.18.6"
not_impacted: "All versions starting from 1.16.13 before 1.17.0, all versions starting
  from v1.17.9 before v1.18.0, all versions startin from v1.18.6"
solution: "Upgrade to versions 1.16.13, 1.17.9, 1.18.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8557"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "d94d0cec-7394-4341-b127-aac8e07c79c9"
versions:
- number: "v1.17.0"
  commit:
    tags:
    - "kubernetes-1.17.0"
    sha: "151c1e40350fc26156093f2c0400eb4b60bb88e1"
    timestamp: "20191211003115"
- number: "v1.18.0"
  commit:
    tags:
    - "kubernetes-1.18.0"
    sha: "e54015b524d2efd26fc3fab5c2259e808d1d357d"
    timestamp: "20200326042227"
- number: "v1.16.13"
  commit:
    tags:
    - "kubernetes-1.16.13"
    sha: "95dded27a4045677ac882943855514319096c4d5"
    timestamp: "20200716002139"
- number: "v1.17.9"
  commit:
    tags:
    - "kubernetes-1.17.9"
    sha: "b0aaaa17b6b3f826a00ac196d007304ebf9b4d64"
    timestamp: "20200716002222"
- number: "v1.18.6"
  commit:
    tags:
    - "kubernetes-1.18.6"
    sha: "a6ba72d3025c835ddfdd437778cb9003eac3c1d0"
    timestamp: "20200716002306"
cwe_ids:
- "CWE-1035"
- "CWE-400"
- "CWE-937"
identifiers:
- "CVE-2020-8557"
