---
identifier: "CVE-2020-8551"
package_slug: "go/github.com/kubernetes/kubelet"
title: "Allocation of Resources Without Limits or Throttling"
description: "The Kubelet component has been found to be vulnerable to a denial of
  service attack via the kubelet API, including the unauthenticated HTTP read-only
  API typically served on port, and the authenticated HTTPS API typically served on
  port "
date: "2020-07-24"
pubdate: "2020-03-27"
affected_range: ">=v1.15.0 <=v1.15.9 || >=v1.16.0 <=v1.16.6 || >=v1.17.0 <=v1.17.2"
fixed_versions: []
affected_versions: "All versions starting from 1.15.0 up to 1.15.9, all versions starting
  from 1.16.0 up to 1.16.6, all versions starting from 1.17.0 up to 1.17.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8551"
cvss_v2: "AV:A/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "22c0700d-f87b-409f-9371-d70a96554e2a"
versions:
- number: "v1.15.0"
  commit:
    tags:
    - "kubernetes-1.15.0"
    sha: "7cd478486025f829aa4c322377f40a8a2856ed82"
    timestamp: "20190620105838"
- number: "v1.16.0"
  commit:
    tags:
    - "kubernetes-1.16.0"
    sha: "da44520956bb0fc3ae2324c454933344c85382d8"
    timestamp: "20190918182654"
- number: "v1.17.0"
  commit:
    tags:
    - "kubernetes-1.17.0"
    sha: "151c1e40350fc26156093f2c0400eb4b60bb88e1"
    timestamp: "20191211003115"
- number: "v1.15.9"
  commit:
    tags:
    - "kubernetes-1.15.9"
    sha: "8b2ff9612c9813fe234b1eccbf79deef46b9acf4"
    timestamp: "20200121212534"
- number: "v1.16.6"
  commit:
    tags:
    - "kubernetes-1.16.6"
    sha: "b0c1fba2f0030d6cd3562b88bbfbcc50b6a9a203"
    timestamp: "20200121212613"
- number: "v1.17.2"
  commit:
    tags:
    - "kubernetes-1.17.2"
    sha: "3411c1317f8960cdbe82b6b1b5496df49b27e832"
    timestamp: "20200121212654"
cwe_ids:
- "CWE-1035"
- "CWE-770"
- "CWE-937"
identifiers:
- "CVE-2020-8551"
