---
identifier: "CVE-2021-25735"
package_slug: "go/github.com/kubernetes/kubelet"
title: "Incorrect Authorization"
description: "A security issue was discovered in kube-apiserver that could allow node
  updates to bypass a Validating Admission Webhook.Validating Admission Webhook does
  not observe some previous fields."
date: "2021-09-13"
pubdate: "2021-09-06"
affected_range: "<v1.18.18||>=v1.19.0 <v1.19.10||>=v1.20.0 <v1.20.6"
fixed_versions:
- "v1.18.18"
- "v1.19.10"
- "v1.20.6"
affected_versions: "All versions before 1.18.18, all versions starting from 1.19.0
  before 1.19.10, all versions starting from 1.20.0 before 1.20.6"
not_impacted: "All versions starting from 1.18.18 before 1.19.0, all versions starting
  from 1.19.10 before 1.20.0, all versions starting from 1.20.6"
solution: "Upgrade to version 1.18.18, 1.19.10, 1.20.6, or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25735"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:H"
uuid: "26c5233b-1803-4da8-97f3-b5fd9eccabae"
versions:
- number: "v1.19.0"
  commit:
    tags:
    - "kubernetes-1.19.0"
    sha: "ac66230628094eb883c92828d00617dd488a0198"
    timestamp: "20200826215147"
- number: "v1.20.0"
  commit:
    tags:
    - "kubernetes-1.20.0"
    sha: "813e574ae28f51d8fa7745338022f4b9623827bb"
    timestamp: "20201208213757"
- number: "v1.18.18"
  commit:
    tags:
    - "kubernetes-1.18.18"
    sha: "f6dfdcae16ddf3c55e533a0ddab3c26d1bdd91e2"
    timestamp: "20210415085016"
- number: "v1.19.10"
  commit:
    tags:
    - "kubernetes-1.19.10"
    sha: "d635c32abd0b293230cbc8b9211c6f287cf9f9d5"
    timestamp: "20210415085053"
- number: "v1.20.6"
  commit:
    tags:
    - "kubernetes-1.20.6"
    sha: "e4efd12eddbf12432141ef9e04582b1cd51808f9"
    timestamp: "20210415085137"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2021-25735"
