---
identifier: "CVE-2021-39226"
identifiers:
- "CVE-2021-39226"
- "GHSA-69j6-29vr-p3j9"
package_slug: "go/github.com/grafana/grafana"
title: "Authentication bypass for viewing and deletions of snapshots"
description: "CVSS Score: 9.8 Critical\nCVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H\n\nWe
  received a security report to [security@grafana.com](mailto:security@grafana.com)
  on 2021-09-15 about a vulnerability in Grafana regarding the snapshot feature. It
  was later identified as affecting Grafana versions from 2.0.1 to 8.1.6. [CVE-2021-39226](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-39226)
  has been assigned to this vulnerability."
date: "2025-10-22"
pubdate: "2021-10-05"
affected_range: "<7.5.11||>=8.0.0 <8.1.6"
fixed_versions:
- "7.5.11"
- "8.1.6"
affected_versions: "All versions before 7.5.11, all versions starting from 8.0.0 before
  8.1.6"
not_impacted: "All versions starting from 7.5.11 before 8.0.0, all versions starting
  from 8.1.6"
solution: "Upgrade to versions 7.5.11, 8.1.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-39226"
- "https://github.com/advisories/GHSA-69j6-29vr-p3j9"
- "https://github.com/grafana/grafana/security/advisories/GHSA-69j6-29vr-p3j9"
- "https://github.com/grafana/grafana/commit/2d456a6375855364d098ede379438bf7f0667269"
- "https://github.com/grafana/grafana"
- "https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-5-11"
- "https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-1-6"
- "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DCKBFUSY6V4VU5AQUYWKISREZX5NLQJT"
- "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/E6ANHRDBXQT6TURLP2THM26ZPDINFBEG"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DCKBFUSY6V4VU5AQUYWKISREZX5NLQJT"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E6ANHRDBXQT6TURLP2THM26ZPDINFBEG"
- "https://security.netapp.com/advisory/ntap-20211029-0008"
- "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2021-39226"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "b7aa7dcb-1659-433d-bc34-8b61743bcbd8"
cwe_ids:
- "CWE-287"
- "CWE-862"
- "CWE-937"
- "CWE-1035"
