---
identifier: "CVE-2018-15727"
identifiers:
- "GHSA-rgjg-66cx-5x9m"
- "CVE-2018-15727"
package_slug: "go/github.com/grafana/grafana"
title: "Improper Authentication"
description: "Grafana 2.x, 3.x, and 4.x before 4.6.4 and 5.x before 5.2.3 allows authentication
  bypass because an attacker can generate a valid \"remember me\" cookie knowing only
  a username of an LDAP or OAuth user."
date: "2023-10-02"
pubdate: "2022-02-15"
affected_range: "<4.6.4||>=5.0.0 <5.2.3"
fixed_versions:
- "4.6.4"
- "5.2.3"
affected_versions: "All versions before 4.6.4, all versions starting from 5.0.0 before
  5.2.3"
not_impacted: "All versions starting from 4.6.4 before 5.0.0, all versions starting
  from 5.2.3"
solution: "Upgrade to versions 4.6.4, 5.2.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-15727"
- "https://github.com/grafana/grafana/commit/7baecf0d0deae0d865e45cf03e082bc0db3f28c3"
- "https://github.com/grafana/grafana/commit/df83bf10a225811927644bdf6265fa80bdea9137"
- "https://access.redhat.com/errata/RHSA-2018:3829"
- "https://access.redhat.com/errata/RHSA-2019:0019"
- "https://grafana.com/blog/2018/08/29/grafana-5.2.3-and-4.6.4-released-with-important-security-fix/"
- "https://www.securityfocus.com/bid/105184"
- "https://github.com/advisories/GHSA-rgjg-66cx-5x9m"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "d365c9dd-01a6-4cf4-a467-f09012d51705"
cwe_ids:
- "CWE-1035"
- "CWE-287"
- "CWE-937"
