---
identifier: "CVE-2025-41115"
identifiers:
- "CVE-2025-41115"
- "GHSA-w62r-7c53-fmc5"
package_slug: "go/github.com/grafana/grafana"
title: "Grafana Incorrect Privilege Assignment vulnerability"
description: "SCIM provisioning was introduced in Grafana Enterprise and Grafana Cloud
  in April to improve how organizations manage users and teams in Grafana by introducing
  automated user lifecycle management.\n\nIn Grafana versions 12.x where SCIM provisioning
  is enabled and configured, a vulnerability in user identity handling allows a malicious
  or compromised SCIM client to provision a user with a numeric externalId, which
  in turn could allow to override internal user IDs and lead to impersonation or privilege
  escalation.\n\nThis vulnerability applies only if all of the following conditions
  are met:\n- `enableSCIM` feature flag set to true\n- `user_sync_enabled` config
  option in the `[auth.scim]` block set to true"
date: "2025-11-27"
pubdate: "2025-11-21"
affected_range: ">=12.0.0 <12.0.7||>=12.1.0 <12.1.4||>=12.2.0 <12.2.2"
fixed_versions:
- "12.0.7"
- "12.1.4"
- "12.2.2"
affected_versions: "All versions starting from 12.0.0 before 12.0.7, all versions
  starting from 12.1.0 before 12.1.4, all versions starting from 12.2.0 before 12.2.2"
not_impacted: "All versions before 12.0.0, all versions starting from 12.0.7 before
  12.1.0, all versions starting from 12.1.4 before 12.2.0, all versions starting from
  12.2.2"
solution: "Upgrade to versions 12.0.7, 12.1.4, 12.2.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-41115"
- "https://github.com/advisories/GHSA-w62r-7c53-fmc5"
- "https://github.com/grafana/grafana/commit/ca5d89812015ef2db3acc62826f73650450b331e"
- "https://github.com/grafana/grafana"
- "https://github.com/grafana/grafana/releases/tag/v12.0.7"
- "https://github.com/grafana/grafana/releases/tag/v12.1.4"
- "https://github.com/grafana/grafana/releases/tag/v12.2.2"
- "https://github.com/grafana/grafana/releases/tag/v12.3.0"
- "https://grafana.com/security/security-advisories/CVE-2025-41115"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H"
uuid: "c0e311ff-a7d2-493c-b0e0-d4fa5bc62053"
cwe_ids:
- "CWE-266"
- "CWE-937"
- "CWE-1035"
