---
identifier: "CVE-2025-62725"
identifiers:
- "CVE-2025-62725"
- "GHSA-gv8h-7v7w-r22q"
package_slug: "go/github.com/docker/compose/v2"
title: "Docker Compose Vulnerable to Path Traversal via OCI Artifact Layer Annotations"
description: "Docker Compose trusts the path information embedded in remote OCI compose
  artifacts. When a layer includes the annotations com.docker.compose.extends or com.docker.compose.envfile,
  Compose joins the attackerâ€‘supplied value from com.docker.compose.file/com.docker.compose.envfile
  with its local cache directory and writes the file there."
date: "2025-10-27"
pubdate: "2025-10-27"
affected_range: "<2.40.2"
fixed_versions:
- "2.40.2"
affected_versions: "All versions before 2.40.2"
not_impacted: "All versions starting from 2.40.2"
solution: "Upgrade to version 2.40.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-62725"
- "https://github.com/advisories/GHSA-gv8h-7v7w-r22q"
- "https://github.com/docker/compose/security/advisories/GHSA-gv8h-7v7w-r22q"
- "https://github.com/docker/compose/commit/69bcb962bfb2ea53b41aa925333d356b577d6176"
- "https://github.com/docker/compose"
uuid: "3acbca16-da92-4caf-bb73-5f4275a1c3a8"
cwe_ids:
- "CWE-20"
- "CWE-937"
- "CWE-1035"
