---
identifier: "GMS-2022-4365"
identifiers:
- "GHSA-9jjv-524m-jm98"
- "GMS-2022-4365"
package_slug: "npm/@netlify/ipx"
title: "Duplicate"
description: "This advisory duplicates another."
date: "2026-01-26"
pubdate: "2022-09-21"
affected_range: "<0"
fixed_versions: []
affected_versions: "None"
not_impacted: "N/A"
solution: "N/A"
urls:
- "https://github.com/netlify/netlify-ipx/security/advisories/GHSA-9jjv-524m-jm98"
- "https://github.com/netlify/netlify-ipx/pull/61"
- "https://github.com/netlify/netlify-ipx/commit/dfa7505a8d47a76fd527570dc40737a61500759b"
- "https://github.com/netlify/netlify-ipx/releases/tag/v1.2.3"
- "https://github.com/advisories/GHSA-9jjv-524m-jm98"
uuid: "74b62f3b-cab8-4107-a16d-8237dd59bb96"
cwe_ids:
- "CWE-1035"
- "CWE-79"
- "CWE-937"
