---
identifier: "CVE-2025-54410"
identifiers:
- "CVE-2025-54410"
- "GHSA-4vq8-7jfc-9cvp"
package_slug: "go/github.com/docker/docker"
title: "Moby firewalld reload removes bridge network isolation"
description: "Moby is an open source container framework developed by Docker Inc.
  that is distributed as Docker Engine, Mirantis Container Runtime, and various other
  downstream projects/products. The Moby daemon component (dockerd), which is developed
  as [moby/moby](https://github.com/moby/moby) is commonly referred to as Docker,
  or Docker Engine.\n\nFirewalld is a daemon used by some Linux distributions to provide
  a dynamically managed firewall. When Firewalld is running, Docker uses its iptables
  backend to create rules, including rules to isolate containers in one bridge network
  from containers in other bridge networks."
date: "2025-12-20"
pubdate: "2025-07-29"
affected_range: "<=25.0.12||>=26.0.0-rc1 <28.0.0"
fixed_versions:
- "28.0.0"
affected_versions: "All versions up to 25.0.12, all versions starting from 26.0.0-rc1
  before 28.0.0"
not_impacted: "All versions after 25.0.12 before 26.0.0-rc1, all versions starting
  from 28.0.0"
solution: "Upgrade to version 28.0.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-54410"
- "https://github.com/advisories/GHSA-4vq8-7jfc-9cvp"
- "https://github.com/moby/moby/security/advisories/GHSA-4vq8-7jfc-9cvp"
- "https://github.com/moby/moby/pull/49443"
- "https://github.com/moby/moby/pull/49728"
- "https://firewalld.org/documentation/howto/reload-firewalld.html"
- "https://github.com/moby/moby"
cvss_v3: "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N"
uuid: "1ddba345-a589-42d4-a082-06c2387cc029"
cwe_ids:
- "CWE-909"
- "CWE-937"
- "CWE-1035"
