---
identifier: "CVE-2024-52003"
identifiers:
- "CVE-2024-52003"
- "GHSA-h924-8g65-j9wg"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Traefik's X-Forwarded-Prefix Header still allows for Open Redirect"
description: "The previously reported open redirect ([GHSA-6qq8-5wq3-86rp](https://github.com/traefik/traefik/security/advisories/GHSA-6qq8-5wq3-86rp))
  is not fixed correctly. The safePrefix function can be tricked to return an absolute
  URL."
date: "2025-10-31"
pubdate: "2024-12-02"
affected_range: "<2.11.14"
fixed_versions:
- "2.11.14"
affected_versions: "All versions before 2.11.14"
not_impacted: "All versions starting from 2.11.14"
solution: "Upgrade to version 2.11.14 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2024-52003"
- "https://github.com/advisories/GHSA-h924-8g65-j9wg"
- "https://github.com/traefik/traefik/security/advisories/GHSA-h924-8g65-j9wg"
- "https://github.com/traefik/traefik/pull/11253"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.14"
- "https://github.com/traefik/traefik/releases/tag/v3.2.1"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N"
cvss_v4: "CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N"
uuid: "5a152c61-3f93-488e-8535-a249c10d200c"
cwe_ids:
- "CWE-601"
- "CWE-937"
- "CWE-1035"
