---
identifier: "CVE-2025-32431"
identifiers:
- "CVE-2025-32431"
- "GHSA-6p68-w45g-48j7"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Traefik has a possible vulnerability with the path matchers"
description: "There is a potential vulnerability in Traefik managing the requests
  using a `PathPrefix`, `Path` or `PathRegex` matcher.\n\nWhen Traefik is configured
  to route the requests to a backend using a matcher based on the path, if the URL
  contains a `/../` in its path, itâ€™s possible to target a backend, exposed using
  another router, by-passing the middlewares chain."
date: "2025-10-31"
pubdate: "2025-04-21"
affected_range: "<2.11.23"
fixed_versions:
- "2.11.23"
affected_versions: "All versions before 2.11.23"
not_impacted: "All versions starting from 2.11.23"
solution: "Upgrade to version 2.11.23 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-32431"
- "https://github.com/advisories/GHSA-6p68-w45g-48j7"
- "https://github.com/traefik/traefik/security/advisories/GHSA-6p68-w45g-48j7"
- "https://github.com/traefik/traefik/pull/11684"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.24"
- "https://github.com/traefik/traefik/releases/tag/v3.3.6"
- "https://github.com/traefik/traefik/releases/tag/v3.4.0-rc2"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
cvss_v4: "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N"
uuid: "3a3a8a3d-75c5-4d71-bf25-ff102ec51d60"
cwe_ids:
- "CWE-22"
- "CWE-937"
- "CWE-1035"
