---
identifier: "CVE-2025-54386"
identifiers:
- "CVE-2025-54386"
- "GHSA-q6gg-9f92-r9wg"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Traefik Client Plugin's Path Traversal Vulnerability Allows Arbitrary File
  Overwrite and Remote Code Execution"
description: "A path traversal vulnerability was discovered in WASM Traefik’s plugin
  installation mechanism. By supplying a maliciously crafted ZIP archive containing
  file paths with `../` sequences, an attacker can overwrite arbitrary files on the
  system outside of the intended plugin directory. This can lead to remote code execution
  (RCE), privilege escalation, persistence, or denial of service.\n**✅ After investigation,
  it is confirmed that no plugins on the [Catalog](https://plugins.traefik.io/plugins)
  were affected. There is no known impact.**"
date: "2025-11-27"
pubdate: "2025-08-01"
affected_range: "<2.11.28"
fixed_versions:
- "2.11.28"
affected_versions: "All versions before 2.11.28"
not_impacted: "All versions starting from 2.11.28"
solution: "Upgrade to version 2.11.28 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-54386"
- "https://github.com/advisories/GHSA-q6gg-9f92-r9wg"
- "https://github.com/traefik/traefik/security/advisories/GHSA-q6gg-9f92-r9wg"
- "https://github.com/traefik/plugin-service/pull/71"
- "https://github.com/traefik/plugin-service/pull/72"
- "https://github.com/traefik/traefik/pull/11911"
- "https://github.com/traefik/traefik/commit/5ef853a0c53068f69a6c229a5815a0dc6e0a8800"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.28"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
cvss_v4: "CVSS:4.0/AV:N/AC:H/AT:P/PR:H/UI:P/VC:H/VI:H/VA:H/SC:L/SI:L/SA:L"
uuid: "8168ef9d-a63c-404f-a3fd-6fbcfdd96aa7"
cwe_ids:
- "CWE-22"
- "CWE-30"
- "CWE-937"
- "CWE-1035"
