---
identifier: "CVE-2022-23632"
identifiers:
- "GHSA-hrhx-6h34-j5hc"
- "CVE-2022-23632"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Improper Certificate Validation"
description: "Traefik is an HTTP reverse proxy and load balancer., Traefik skips the
  router transport layer security (TLS) configuration when the host header is a fully
  qualified domain name (FQDN). For a request, the TLS configuration choice can be
  different than the router choice, which implies the use of a wrong TLS configuration.
  When sending a request using FQDN handled by a router configured with a dedicated
  TLS configuration, the TLS configuration falls back to the default configuration
  that might not correspond to the configured one. If the CNAME flattening is enabled,
  the selected TLS configuration is the SNI one and the routing uses the CNAME value,
  so this can skip the expected TLS configuration. contains a patch for this issue.
  As a workaround, one may add the FDQN to the host rule. However, there is no workaround
  if the CNAME flattening is enabled."
date: "2022-02-17"
pubdate: "2022-02-16"
affected_range: "<v2.6.1"
fixed_versions:
- "v2.6.1"
affected_versions: "All versions before 2.6.1"
not_impacted: "All versions starting from 2.6.1"
solution: "Upgrade to version 2.6.1 or above."
urls:
- "https://github.com/traefik/traefik/security/advisories/GHSA-hrhx-6h34-j5hc"
- "https://github.com/advisories/GHSA-hrhx-6h34-j5hc"
uuid: "dea94c23-d790-4f68-a1e1-e3575286a5ef"
cwe_ids:
- "CWE-1035"
- "CWE-295"
- "CWE-937"
versions:
- number: "v2.6.1"
  commit:
    tags:
    - "v2.6.1"
    sha: "84a081054688349fa4e2513599e3bf2395331492"
    timestamp: "20220214164408"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
