---
identifier: "GHSA-3wqc-mwfx-672p"
identifiers:
- "GHSA-3wqc-mwfx-672p"
package_slug: "go/github.com/traefik/traefik/v2"
title: "Duplicate"
description: "This advisory duplicates another."
date: "2026-01-26"
pubdate: "2025-04-18"
affected_range: "<0"
fixed_versions: []
affected_versions: "None"
not_impacted: "N/A"
solution: "N/A"
urls:
- "https://github.com/advisories/GHSA-3wqc-mwfx-672p"
- "https://github.com/traefik/traefik/security/advisories/GHSA-3wqc-mwfx-672p"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.24"
- "https://github.com/traefik/traefik/releases/tag/v3.3.6"
- "https://github.com/traefik/traefik/releases/tag/v3.4.0-rc2"
- "https://security.snyk.io/vuln/SNYK-CHAINGUARDLATEST-TRAEFIK33-9403297"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "0cdd320e-234a-439f-8560-ca81997aff60"
cwe_ids:
- "CWE-1286"
- "CWE-937"
- "CWE-1035"
