---
identifier: "CVE-2018-1999040"
package_slug: "maven/org.csanchez.jenkins.plugins/kubernetes"
title: "Information Exposure"
description: "An exposure of sensitive information vulnerability exists in the Jenkins
  Kubernetes Plugin in `KubernetesCloud.java`. The vulnerability allows attackers
  to capture credentials with a known credentials ID stored in Jenkins."
date: "2019-10-03"
pubdate: "2018-08-01"
affected_range: "(,1.10.1]"
fixed_versions:
- "1.11"
affected_versions: "All versions up to 1.10.1"
not_impacted: "All versions after 1.10.1"
solution: "Upgrade to version 1.11 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1999040"
- "https://jenkins.io/security/advisory/2018-07-30/#SECURITY-1016"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:N/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "f8b003db-3035-4926-85ff-a13a3deb66c9"
cwe_ids:
- "CWE-1035"
- "CWE-200"
- "CWE-937"
identifiers:
- "CVE-2018-1999040"
