---
identifier: "CVE-2021-25742"
identifiers:
- "CVE-2021-25742"
package_slug: "go/github.com/kubernetes/ingress-nginx"
title: "Improper Input Validation"
description: "A security issue was discovered in ingress-nginx where a user that can
  create or update ingress objects can use the custom snippets feature to obtain all
  secrets in the cluster."
date: "2021-12-15"
pubdate: "2021-10-29"
affected_range: "<v0.49.1 || =v1.0.0"
fixed_versions:
- "v0.49.1"
- "v1.0.1"
affected_versions: "All versions before 0.49.1, version 1.0.0"
not_impacted: "All versions starting from 0.49.1 before 1.0.0, all versions
  starting from 1.0.1"
solution: "Upgrade to version 0.49.1, 1.0.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25742"
- "https://groups.google.com/g/kubernetes-security-announce/c/mT4JJxi9tQY"
- "https://github.com/kubernetes/ingress-nginx/issues/7837"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N"
uuid: "9d703ab9-25b2-4054-9930-ae859cd75df5"
cwe_ids:
- "CWE-1035"
- "CWE-937"
versions:
- number: "v1.0.0"
  commit:
    tags:
    - "controller-v1.0.0-alpha.2"
    sha: "73943ad6f187e09f2ce2855c80a854f54fceaa03"
    timestamp: "20210709214034"
