---
identifier: "CVE-2020-8553"
package_slug: "go/github.com/kubernetes/ingress-nginx"
title: "Externally Controlled Reference to a Resource in Another Sphere"
description: "The Kubernetes ingress-nginx component allows a user with the ability
  to create namespaces and to read and create ingress objects to overwrite the password
  file of another ingress which uses `nginx.ingress.kubernetes.io/auth-type`."
date: "2020-08-04"
pubdate: "2020-07-29"
affected_range: "<v0.28.0"
fixed_versions:
- "v0.28.0"
affected_versions: "All versions before 0.28.0"
not_impacted: "All versions starting from 0.28.0"
solution: "Upgrade to version 0.28.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8553"
cvss_v2: "AV:N/AC:M/Au:S/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N"
uuid: "60547ecd-fa00-4afe-9c51-4044bc8eecfa"
versions:
- number: "v0.28.0"
  commit:
    tags:
    - "nginx-0.28.0"
    sha: "1f93cb8f35be8cc689d43e8b34ed1049e09e4287"
    timestamp: "20200128120413"
cwe_ids:
- "CWE-1035"
- "CWE-610"
- "CWE-937"
identifiers:
- "CVE-2020-8553"
