---
identifier: "CVE-2020-16248"
package_slug: "go/github.com/prometheus/blackbox_exporter"
title: "Server-Side Request Forgery (SSRF)"
description: "** DISPUTED ** Prometheus Blackbox Exporter allows `/probe?target=`
  SSRF. NOTE: follow-on discussion suggests that this might plausibly be interpreted
  as both intended functionality and also a vulnerability."
date: "2020-08-12"
pubdate: "2020-08-09"
affected_range: "<=v0.17.0"
fixed_versions:
- "v0.18.0"
affected_versions: "All versions up to 0.17.0"
not_impacted: "All versions after 0.17.0"
solution: "Upgrade to version 0.18.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-16248"
- "https://prometheus.io/docs/operating/security/#exporters"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:N/A:N"
uuid: "487ed235-1bea-4b02-94ec-ac22a7159d0b"
versions:
- number: "v0.17.0"
  commit:
    tags:
    - "v0.17.0"
    sha: "b229a9abd2d52e11a92fda06d4a70644076496e9"
    timestamp: "20200619113027"
- number: "v0.18.0"
  commit:
    tags:
    - "v0.18.0"
    sha: "ab331b120d0c0eae35de0f1416b0d3cc469b302b"
    timestamp: "20201012094517"
cwe_ids:
- "CWE-1035"
- "CWE-918"
- "CWE-937"
identifiers:
- "CVE-2020-16248"
