---
identifier: "CVE-2025-32431"
identifiers:
- "CVE-2025-32431"
- "GHSA-6p68-w45g-48j7"
package_slug: "go/github.com/traefik/traefik"
title: "Traefik has a possible vulnerability with the path matchers"
description: "There is a potential vulnerability in Traefik managing the requests
  using a `PathPrefix`, `Path` or `PathRegex` matcher.\n\nWhen Traefik is configured
  to route the requests to a backend using a matcher based on the path, if the URL
  contains a `/../` in its path, itâ€™s possible to target a backend, exposed using
  another router, by-passing the middlewares chain."
date: "2025-10-31"
pubdate: "2025-04-21"
affected_range: "<=1.7.34"
fixed_versions: []
affected_versions: "All versions up to 1.7.34"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-32431"
- "https://github.com/advisories/GHSA-6p68-w45g-48j7"
- "https://github.com/traefik/traefik/security/advisories/GHSA-6p68-w45g-48j7"
- "https://github.com/traefik/traefik/pull/11684"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.24"
- "https://github.com/traefik/traefik/releases/tag/v3.3.6"
- "https://github.com/traefik/traefik/releases/tag/v3.4.0-rc2"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
cvss_v4: "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N"
uuid: "3d8bf212-e246-49e1-83da-baee08204c7c"
cwe_ids:
- "CWE-22"
- "CWE-937"
- "CWE-1035"
