---
identifier: "CVE-2025-66490"
identifiers:
- "CVE-2025-66490"
- "GHSA-gm3x-23wp-hc2c"
package_slug: "go/github.com/traefik/traefik"
title: "Path Normalization Bypass in Traefik Router + Middleware Rules"
description: "There is a potential vulnerability in Traefik managing the requests
  using a `PathPrefix`, `Path` or `PathRegex` matcher.\n\nWhen Traefik is configured
  to route the requests to a backend using a matcher based on the path; if the request
  path contains an encoded restricted character from the following set **('/', '\\',
  'Null', ';', '?', '#')**, itâ€™s possible to target a backend, exposed using another
  router, by-passing the middlewares chain.\n\nAccess Control Bypass:\nAny endpoint
  intended to be blocked (e.g., admin/debug/beta APIs) can be accessed by URL-encoding
  slashes or other characters.\n\nThis could lead to:\n\n- Unauthorized access to
  restricted endpoints\n- Execution of protected internal functionality\n- Potential
  privilege escalation\n- Bypass of security policies enforced via Traefik routing
  rules\n</details>"
date: "2025-12-08"
pubdate: "2025-12-08"
affected_range: "<=1.7.34"
fixed_versions: []
affected_versions: "All versions up to 1.7.34"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-66490"
- "https://github.com/advisories/GHSA-gm3x-23wp-hc2c"
- "https://github.com/traefik/traefik/security/advisories/GHSA-gm3x-23wp-hc2c"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.32"
- "https://github.com/traefik/traefik/releases/tag/v3.6.4"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
cvss_v4: "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:L/SI:L/SA:N"
uuid: "062f92ee-d6b3-43f1-82fe-e5b820a6475d"
cwe_ids:
- "CWE-436"
- "CWE-937"
- "CWE-1035"
