---
identifier: "CVE-2025-47952"
identifiers:
- "CVE-2025-47952"
- "GHSA-vrch-868g-9jx5"
package_slug: "go/github.com/traefik/traefik"
title: "Traefik allows path traversal using url encoding"
description: "Path traversal with \"/../\" using URL encodings (\"/%2e%2e\") allows
  for circumventing routing rules."
date: "2025-10-31"
pubdate: "2025-05-28"
affected_range: "<=1.7.34"
fixed_versions: []
affected_versions: "All versions up to 1.7.34"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-47952"
- "https://github.com/advisories/GHSA-vrch-868g-9jx5"
- "https://github.com/traefik/traefik/security/advisories/GHSA-vrch-868g-9jx5"
- "https://github.com/traefik/traefik/commit/08d5dfee0164aa54dd44a467870042e18e8d3f00"
- "https://github.com/traefik/traefik"
- "https://github.com/traefik/traefik/releases/tag/v2.11.25"
- "https://github.com/traefik/traefik/releases/tag/v3.4.1"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
cvss_v4: "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N"
uuid: "084f86be-5309-471c-ae49-dc83153c143e"
cwe_ids:
- "CWE-22"
- "CWE-937"
- "CWE-1035"
