---
identifier: "CVE-2020-8559"
package_slug: "go/github.com/kubernetes/apimachinery"
title: "URL Redirection to Untrusted Site (Open Redirect)"
description: "The Kubernetes kube-apiserver is vulnerable to an unvalidated redirect
  on proxied upgrade requests that could allow an attacker to escalate privileges
  from a node compromise to a full cluster compromise."
date: "2020-07-27"
pubdate: "2020-07-22"
affected_range: ">=v1.7.6 <=v1.16.13 || >=v1.17.0 <v1.17.9 || >=v1.18.0 <v1.18.6"
fixed_versions:
- "0.19.0-rc.1"
affected_versions: "All versions starting from 1.7.6 up to 1.16.13, all versions starting
  from 1.17.0 before 1.17.9, all versions starting from 1.18.0 before 1.18.6"
not_impacted: "All versions before 1.7.6, all versions after 1.16.13 before 1.17.0,
  all versions starting from 1.17.9 before 1.18.0, all versions starting from 1.18.6"
solution: "Upgrade to version 0.19.0-rc.1. *Note*: 0.19.0-rc.1 may be an unstable
  version. Use caution."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8559"
cvss_v2: "AV:N/AC:M/Au:S/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:H/I:H/A:H"
uuid: "91659631-ed64-4396-9877-2bef9e006ee7"
versions:
- number: "v1.7.6"
  commit:
    tags:
    - "kubernetes-1.7.6"
    sha: "0e0d21ba19a64a27f4f991627caedb5888dfeab7"
    timestamp: "20170824173024"
- number: "v1.17.0"
  commit:
    tags:
    - "kubernetes-1.17.0"
    sha: "5a8acaf43eb1db969a3d0acbe9628b96cb336893"
    timestamp: "20191121185448"
- number: "v1.18.0"
  commit:
    tags:
    - "kubernetes-1.18.0"
    sha: "6e1584e73d7971c58a47aed9135e6bc9fa8cf1fc"
    timestamp: "20200321215243"
- number: "v0.19.0-rc.1"
  commit:
    tags:
    - "v0.19.0-rc.1"
    sha: "fe7fed6f51bc34d9e33edb3a59be68977173f326"
    timestamp: "20200712191229"
- number: "v1.16.13"
  commit:
    tags:
    - "kubernetes-1.16.13"
    sha: "210e0f6fe9de6fe551cff97fa5c6b6333ca86e0e"
    timestamp: "20200712223233"
- number: "v1.17.9"
  commit:
    tags:
    - "kubernetes-1.17.9"
    sha: "3787b08134b643227580d92fa5e5a4af744a586d"
    timestamp: "20200712225033"
- number: "v1.18.6"
  commit:
    tags:
    - "kubernetes-1.18.6"
    sha: "b78bcf6560d428de8162fbfa1b97674c1bd897a1"
    timestamp: "20200713012633"
cwe_ids:
- "CWE-1035"
- "CWE-601"
- "CWE-937"
identifiers:
- "CVE-2020-8559"
