---
identifier: "CVE-2020-27534"
package_slug: "go/github.com/docker/libcontainer"
title: "Path Traversal"
description: "`util/binfmt_misc/check.go` in Builder of Docker Engine calls `os.OpenFile`
  with a potentially unsafe qemu-check temporary pathname, constructed with an empty
  first argument in an `ioutil.TempDir` call."
date: "2021-01-05"
pubdate: "2020-12-30"
affected_range: "<19.03.9"
fixed_versions:
- "19.03.9"
affected_versions: "All versions before 19.03.9"
not_impacted: "All versions starting from 19.03.9"
solution: "Upgrade to version 19.03.9 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-27534"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
uuid: "8b2c4150-3767-4234-9fb6-3de9cd40a7f9"
cwe_ids:
- "CWE-1035"
- "CWE-22"
- "CWE-937"
identifiers:
- "CVE-2020-27534"
