---
identifier: "CVE-2019-3826"
package_slug: "go/github.com/prometheus/prometheus"
title: "False Positive"
description: "This advisory has been marked as a False Positive and has been removed."
# title: "Cross-site Scripting"
# description: "A stored, DOM based, cross-site scripting (XSS) flaw was found in Prometheus.
#  An attacker could exploit this by convincing an authenticated user to visit a crafted
#  URL on a Prometheus server, allowing for the execution and persistent storage of
#  arbitrary scripts."
date: "2019-10-09"
pubdate: "2019-03-26"
affected_range: "<0"
fixed_versions:
- "v2.7.1"
affected_versions: "All versions before 2.7.1"
_git_import_path: "go/github.com/prometheus/prometheus/web/ui"
not_impacted: "All versions starting from 2.7.1."
solution: "Upgrade to version 2.7.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-3826"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3826"
cvss_v2: "AV:N/AC:M/Au:N/C:N/I:P/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
uuid: "c69b7637-ea59-4753-9e3f-9b6b9e97166f"
versions:
- number: "v2.7.1"
  commit:
    tags:
    - "v2.7.1"
    sha: "876a1c06456c30f494f845678c93e9163e51c711"
    timestamp: "20190131121325"
cwe_ids:
- "CWE-1035"
- "CWE-79"
- "CWE-937"
identifiers:
- "CVE-2019-3826"
