---
identifier: "CVE-2025-64443"
identifiers:
- "CVE-2025-64443"
- "GHSA-46gc-mwh4-cc5r"
package_slug: "go/github.com/docker/mcp-gateway"
title: "Docker MCP Plugin and Docker MCP Gateway have DNS Rebinding vulnerability
  when running in sse or streaming mode"
description: "When ran in sse or streaming mode (--transport), the Docker MCP Gateway
  is vulnerable to a DNS rebinding attack.\n\nVulnerability allows for Browser-Based
  exploitation of any MCP servers that are executing within the Docker MCP Gateway.
  Any tools or other features exposed by MCP servers can be manipulated by an attacker
  who is able to get a victim to visit a malicious website, or if a victim is served
  a malicious advertisement.\n\nThe MCP Gateway is not prone to this attack when started
  in its default stdio mode, which does not listen on any network ports."
date: "2025-12-03"
pubdate: "2025-12-03"
affected_range: "<0.28.0"
fixed_versions:
- "0.28.0"
affected_versions: "All versions before 0.28.0"
not_impacted: "All versions starting from 0.28.0"
solution: "Upgrade to version 0.28.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-64443"
- "https://github.com/advisories/GHSA-46gc-mwh4-cc5r"
- "https://github.com/docker/mcp-gateway/security/advisories/GHSA-46gc-mwh4-cc5r"
- "https://github.com/docker/mcp-gateway/pull/190"
- "https://github.com/docker/mcp-gateway/commit/fe073985c8eb6e0c9317d2f198c07686f70ea06d"
- "https://github.com/docker/mcp-gateway"
- "https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#security-warning"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H"
cvss_v4: "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:L/VI:H/VA:N/SC:H/SI:H/SA:H"
uuid: "c531d4f5-e6e0-4bca-90a8-2483249f3f22"
cwe_ids:
- "CWE-749"
- "CWE-937"
- "CWE-1035"
