---
identifier: "CVE-2025-13281"
identifiers:
- "CVE-2025-13281"
- "GHSA-r6j8-c6r2-37rr"
package_slug: "go/k8s.io/kubernetes"
title: "kube-controller-manager is vulnerable to half-blind Server Side Request Forgery
  through in-tree Portworx StorageClass"
description: "A half-blind Server Side Request Forgery (SSRF) vulnerability exists
  in kube-controller-manager when using the in-tree Portworx StorageClass. This vulnerability
  allows authorized users to leak arbitrary information from unprotected endpoints
  in the control planeâ€™s host network (including link-local or loopback services)."
date: "2025-12-20"
pubdate: "2025-12-15"
affected_range: "<1.32.10||>=1.33.0-alpha.0 <1.33.6||>=1.34.0-alpha.0 <1.34.2"
fixed_versions:
- "1.32.10"
- "1.33.6"
- "1.34.2"
affected_versions: "All versions before 1.32.10, all versions starting from 1.33.0-alpha.0
  before 1.33.6, all versions starting from 1.34.0-alpha.0 before 1.34.2"
not_impacted: "All versions starting from 1.32.10 before 1.33.0-alpha.0, all versions
  starting from 1.33.6 before 1.34.0-alpha.0, all versions starting from 1.34.2"
solution: "Upgrade to versions 1.32.10, 1.33.6, 1.34.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-13281"
- "https://github.com/advisories/GHSA-r6j8-c6r2-37rr"
- "https://github.com/kubernetes/kubernetes/issues/135525"
- "https://github.com/kubernetes/kubernetes/commit/7506ce804c20696ba32cdb72126270ceaed06e24"
- "https://github.com/kubernetes/kubernetes/commit/97650c1c4fe15cbb7756ba95b3edc8a8665063ca"
- "https://github.com/kubernetes/kubernetes/commit/dbe17dfe7773563eac95534040f413ada6d2b421"
- "https://github.com/kubernetes/kubernetes"
- "https://groups.google.com/g/kubernetes-security-announce/c/EORqZg0k1l4/m/TtD-q0v7AgAJ"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:C/C:H/I:N/A:N"
uuid: "9152e15f-7889-46eb-93b7-795ae6deb05f"
cwe_ids:
- "CWE-918"
- "CWE-937"
- "CWE-1035"
