---
identifier: "CVE-2018-1002100"
identifiers:
- "CVE-2018-1002100"
- "GHSA-2jq6-ffph-p4h8"
package_slug: "go/k8s.io/kubernetes"
title: "Kubernetes arbitrary file overwrite"
description: "In Kubernetes versions 1.5.x, 1.6.x, 1.7.x, 1.8.x, and prior to version
  1.9.6, the kubectl cp command insecurely handles tar data returned from the container,
  and can be caused to overwrite arbitrary local files."
date: "2026-01-16"
pubdate: "2022-05-13"
affected_range: ">=1.5.0-alpha.0 <1.9.6"
fixed_versions:
- "1.9.6"
affected_versions: "All versions starting from 1.5.0-alpha.0 before 1.9.6"
not_impacted: "All versions before 1.5.0-alpha.0, all versions starting from 1.9.6"
solution: "Upgrade to version 1.9.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1002100"
- "https://github.com/advisories/GHSA-2jq6-ffph-p4h8"
- "https://github.com/kubernetes/kubernetes/issues/61297"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1564305"
- "https://github.com/kubernetes/kubernetes"
- "https://hansmi.ch/articles/2018-04-openshift-s2i-security"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N"
uuid: "7ca6c4dc-4613-4f5b-ae22-509a126490d0"
cwe_ids:
- "CWE-20"
- "CWE-937"
- "CWE-1035"
