---
identifier: "CVE-2018-1002101"
identifiers:
- "GHSA-wqwf-x5cj-rg56"
- "CVE-2018-1002101"
package_slug: "go/k8s.io/kubernetes"
title: "Kubernetes Arbitrary Command Injection"
description: "In Kubernetes versions 1.9.0-1.9.9, 1.10.0-1.10.5, and 1.11.0-1.11.1,
  user input was handled insecurely while setting up volume mounts on Windows nodes,
  which could lead to command line argument injection."
date: "2023-10-02"
pubdate: "2022-02-15"
affected_range: ">=1.9.0 <1.9.10||>=1.10.0 <1.10.6||>=1.11.0 <1.11.2"
fixed_versions:
- "1.9.10"
- "1.10.6"
- "1.11.2"
affected_versions: "All versions starting from 1.9.0 before 1.9.10, all versions starting
  from 1.10.0 before 1.10.6, all versions starting from 1.11.0 before 1.11.2"
not_impacted: "All versions before 1.9.0, all versions starting from 1.9.10 before
  1.10.0, all versions starting from 1.10.6 before 1.11.0, all versions starting from
  1.11.2"
solution: "Upgrade to versions 1.9.10, 1.10.6, 1.11.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1002101"
- "https://github.com/kubernetes/kubernetes/issues/65750"
- "https://github.com/kubernetes/kubernetes/pull/65751"
- "https://github.com/kubernetes/kubernetes/commit/d65039c56ce4de5f2efdc38aa1284eeb95f89169"
- "https://security.netapp.com/advisory/ntap-20190416-0008/"
- "http://www.securityfocus.com/bid/106238"
- "https://github.com/advisories/GHSA-wqwf-x5cj-rg56"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "6bf5afcf-c052-4ae2-92bf-b1183e39237f"
cwe_ids:
- "CWE-1035"
- "CWE-937"
