---
identifier: "CVE-2020-8551"
identifiers:
- "GHSA-qhm4-jxv7-j9pq"
- "CVE-2020-8551"
package_slug: "go/k8s.io/kubernetes"
title: "Allocation of Resources Without Limits or Throttling"
description: "The Kubelet component in versions 1.15.0-1.15.9, 1.16.0-1.16.6, and
  1.17.0-1.17.2 has been found to be vulnerable to a denial of service attack via
  the kubelet API, including the unauthenticated HTTP read-only API typically served
  on port 10255, and the authenticated HTTPS API typically served on port 10250."
date: "2023-09-18"
pubdate: "2022-02-15"
affected_range: ">=1.15.0 <1.15.10||>=1.16.0 <1.16.6||>=1.17.0 <1.17.2"
fixed_versions:
- "1.15.10"
- "1.16.6"
- "1.17.2"
affected_versions: "All versions starting from 1.15.0 before 1.15.10, all versions
  starting from 1.16.0 before 1.16.6, all versions starting from 1.17.0 before 1.17.2"
not_impacted: "All versions before 1.15.0, all versions starting from 1.15.10 before
  1.16.0, all versions starting from 1.16.6 before 1.17.0, all versions starting from
  1.17.2"
solution: "Upgrade to versions 1.15.10, 1.16.6, 1.17.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-8551"
- "https://github.com/kubernetes/kubernetes/issues/89377"
- "https://github.com/kubernetes/kubernetes/pull/87913"
- "https://github.com/kubernetes/kubernetes/commit/9802bfcec0580169cffce2a3d468689a407fa7dc"
- "https://groups.google.com/forum/#!topic/kubernetes-security-announce/2UOlsba2g0s"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3SOCLOPTSYABTE4CLTSPDIFE6ZZZR4LX/"
- "https://security.netapp.com/advisory/ntap-20200413-0003/"
- "https://github.com/advisories/GHSA-qhm4-jxv7-j9pq"
cvss_v2: "AV:A/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "24b1db54-9d3d-4ccc-bb48-74907d9ae362"
cwe_ids:
- "CWE-1035"
- "CWE-770"
- "CWE-937"
