---
identifier: "CVE-2019-1002101"
identifiers:
- "GHSA-34jx-wx69-9x8v"
- "CVE-2019-1002101"
package_slug: "go/k8s.io/kubernetes"
title: "Improper Link Resolution Before File Access ('Link Following')"
description: "The kubectl cp command allows copying files between containers and the
  user machine. To copy files from a container, Kubernetes creates a tar inside the
  container, copies it over the network, and kubectl unpacks it on the user’s machine.
  If the tar binary in the container is malicious, it could run any code and output
  unexpected, malicious results. An attacker could use this to write files to any
  path on the user’s machine when kubectl cp is called, limited only by the system
  permissions of the local user. The untar function can both create and follow symbolic
  links. The issue is resolved in kubectl v1.11.9, v1.12.7, v1.13.5, and v1.14.0."
date: "2023-09-18"
pubdate: "2022-02-15"
affected_range: "<1.11.9||>=1.12.0 <1.12.7||>=1.13.0 <1.13.5"
fixed_versions:
- "1.11.9"
- "1.12.7"
- "1.13.5"
affected_versions: "All versions before 1.11.9, all versions starting from 1.12.0
  before 1.12.7, all versions starting from 1.13.0 before 1.13.5"
not_impacted: "All versions starting from 1.11.9 before 1.12.0, all versions starting
  from 1.12.7 before 1.13.0, all versions starting from 1.13.5"
solution: "Upgrade to versions 1.11.9, 1.12.7, 1.13.5 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-1002101"
- "https://github.com/kubernetes/kubernetes/pull/75037"
- "https://github.com/kubernetes/kubernetes/commit/47063891dd782835170f500a83f37cc98c3c1013"
- "https://access.redhat.com/errata/RHBA-2019:0619"
- "https://access.redhat.com/errata/RHBA-2019:0620"
- "https://access.redhat.com/errata/RHBA-2019:0636"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BPV2RE5RMOGUVP5WJMXKQJZUBBLAFZPZ/"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QZB7E3DOZ5WDG46XAIU6K32CXHXPXB2F/"
- "https://www.twistlock.com/labs-blog/disclosing-directory-traversal-vulnerability-kubernetes-copy-cve-2019-1002101/"
- "http://www.openwall.com/lists/oss-security/2019/06/21/1"
- "http://www.openwall.com/lists/oss-security/2019/08/05/5"
- "http://www.securityfocus.com/bid/107652"
- "https://github.com/advisories/GHSA-34jx-wx69-9x8v"
cvss_v2: "AV:N/AC:M/Au:N/C:N/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N"
uuid: "04747e30-5ef7-4c15-a50e-ab576d0de89e"
cwe_ids:
- "CWE-1035"
- "CWE-59"
- "CWE-937"
