---
identifier: "CVE-2019-1002100"
identifiers:
- "CVE-2019-1002100"
- "GHSA-q4rr-64r9-fwgf"
package_slug: "go/k8s.io/kubernetes"
title: "Kubernetes DoS Vulnerability"
description: "In all Kubernetes versions prior to v1.11.8, v1.12.6, and v1.13.4, users
  that are authorized to make patch requests to the Kubernetes API Server can send
  a specially crafted patch of type \"json-patch\" (e.g. `kubectl patch --type json`
  or `\"Content-Type: application/json-patch+json\"`) that consumes excessive resources
  while processing, causing a Denial of Service on the API Server."
date: "2026-01-16"
pubdate: "2022-05-13"
affected_range: ">=1.0.0 <=1.10.14||>=1.11.0 <1.11.8||>=1.12.0 <1.12.6||>=1.13.0 <1.13.4"
fixed_versions:
- "1.11.8"
- "1.12.6"
- "1.13.4"
affected_versions: "All versions starting from 1.0.0 up to 1.10.14, all versions starting
  from 1.11.0 before 1.11.8, all versions starting from 1.12.0 before 1.12.6, all
  versions starting from 1.13.0 before 1.13.4"
not_impacted: "All versions before 1.0.0, all versions after 1.10.14 before 1.11.0,
  all versions starting from 1.11.8 before 1.12.0, all versions starting from 1.12.6
  before 1.13.0, all versions starting from 1.13.4"
solution: "Upgrade to versions 1.11.8, 1.12.6, 1.13.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-1002100"
- "https://github.com/advisories/GHSA-q4rr-64r9-fwgf"
- "https://github.com/kubernetes/kubernetes/issues/74534"
- "https://access.redhat.com/errata/RHSA-2019:1851"
- "https://access.redhat.com/errata/RHSA-2019:3239"
- "https://github.com/kubernetes/kubernetes"
- "https://groups.google.com/forum/#!topic/kubernetes-announce/vmUUNkYfG9g"
- "https://security.netapp.com/advisory/ntap-20190416-0002"
- "https://web.archive.org/web/20210125011246/https://www.securityfocus.com/bid/107290"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "763aff8a-4dfd-4942-a07b-7fea6bee8b59"
cwe_ids:
- "CWE-770"
- "CWE-937"
- "CWE-1035"
